import type { McaClause } from '../types';

/**
 * The Permission to Release — a preamble and seven numbered sections.
 *
 * PHASE 0 RECORDS THIS DOCUMENT AS HAVING ZERO CLAUSES. It has eight.
 */
export const PERMISSION_TO_RELEASE_SECTIONS: McaClause[] = [
  {
    slug: 'permission-to-release.preamble',
    version: 1,
    instrument: 'permission-to-release',
    kind: 'clause',
    unnumberedReason: 'Authorization lead-in identifying the person and merchant who give the following permissions.',
    includeWhen: null,
    heading: 'Person Giving Authorization',
    body: 'I, ___________«1»___________, an authorized officer or owner of _____________«2»______________ (the “Merchant”), doing business as _____________«3»______________, with principal place of business at ______________________________«4»______________________________, hereby grant the following authorizations to ________«9»________ (“Buyer”) and its agents, servicers, successors, and assigns:',
    section: 'authorisations',
    sortKey: 10,
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
  },
  {
    slug: 'permission-to-release.trade-landlord-and-bank-information',
    version: 1,
    instrument: 'permission-to-release',
    kind: 'clause',
    includeWhen: null,
    heading: 'Trade, Landlord, and Bank Information',
    body: "Merchant authorizes Buyer to obtain trade, landlord, and bank information from any vendors, suppliers, landlord/mortgagor, banks, creditors, brokers, and payment processors with whom Merchant has or has had a business relationship. This information will be used for the purpose of (a) underwriting Merchant's qualification for funding through Buyer, (b) ongoing program qualification monitoring during the term of any agreement between Merchant and Buyer, and (c) collection upon any breach of an agreement between Merchant and Buyer.",
    section: 'authorisations',
    sortKey: 20,
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
  },
  {
    slug: 'permission-to-release.banking-brokerage-and-processing-history',
    version: 1,
    instrument: 'permission-to-release',
    kind: 'clause',
    includeWhen: null,
    heading: 'Banking, Brokerage, and Processing History',
    body: "Merchant authorizes any of its banks, brokers, payment processors, and credit reporting agencies (collectively, “Information Sources”) to provide Buyer with Merchant's banking, brokerage, and processing history, including but not limited to (i) account balances and activity records, (ii) processing volume and chargeback history, (iii) information necessary to verify the amount of Future Receipts previously processed and any fees that may have been charged, and (iv) any other information necessary to determine Merchant's qualification or continuation in any funding program offered by Buyer or to support collection upon a breach of any agreement between Merchant and Buyer.",
    section: 'authorisations',
    sortKey: 30,
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
  },
  {
    slug: 'permission-to-release.credit-bureau-authorization',
    version: 1,
    instrument: 'permission-to-release',
    kind: 'clause',
    includeWhen: null,
    heading: 'Credit Bureau Authorization',
    body: 'Merchant and any Personal Guarantor under the FRPA hereby authorize Buyer to obtain credit reports and credit-bureau information regarding Merchant and the Personal Guarantor, individually, from any of Equifax, Experian, TransUnion, Dun & Bradstreet, and any other consumer reporting agency or commercial credit bureau, for the permissible purposes of (a) underwriting any commercial financing offer extended by Buyer, (b) ongoing creditworthiness review during the term of any agreement between Merchant and Buyer, and (c) collection upon any breach. Merchant and Personal Guarantor acknowledge that Buyer may obtain such credit reports periodically without further consent.',
    section: 'authorisations',
    sortKey: 40,
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-01',
        findings: ['permission-guarantor-bound-without-signing', 'ptr-no-guarantor-signature-line'],
      },
      { review: 'REVIEW-02', findings: ['frpa-4-3-consumer-report-authority-depends-on-a-separate-instrument'] },
    ],
  },
  {
    slug: 'permission-to-release.fair-credit-reporting-act-acknowledgment',
    version: 1,
    instrument: 'permission-to-release',
    kind: 'clause',
    includeWhen: null,
    heading: 'Fair Credit Reporting Act Acknowledgment',
    body: "Merchant and Personal Guarantor acknowledge that Buyer's credit-bureau pulls regarding the Personal Guarantor are subject to the Fair Credit Reporting Act (15 U.S.C. §1681 et seq.). The Personal Guarantor’s signature below constitutes the “written instructions” of the consumer required for permissible-purpose credit-report access under FCRA §604(a)(2). If any commercial financing application is denied based in whole or in part on information obtained from a consumer reporting agency, Buyer shall provide an adverse-action notice in accordance with FCRA §615(a). Personal Guarantor has the right, upon request, to be informed of the name and address of any consumer reporting agency from which Buyer obtained a credit report regarding Personal Guarantor.",
    section: 'authorisations',
    sortKey: 50,
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-01',
        findings: [
          'permission-guarantor-bound-without-signing',
          'ptr-615a-rights-understated-as-upon-request',
          'ptr-no-guarantor-signature-line',
          'ptr-written-instructions-sourced-to-unsigned-frpa',
        ],
      },
      { review: 'REVIEW-02', findings: ['frpa-4-3-consumer-report-authority-depends-on-a-separate-instrument'] },
    ],
  },
  {
    slug: 'permission-to-release.continuing-authorization-reliance',
    version: 1,
    instrument: 'permission-to-release',
    kind: 'clause',
    includeWhen: null,
    heading: 'Continuing Authorization; Reliance',
    body: 'This Permission is a continuing authorization, effective from the date set forth above and continuing throughout the term of any agreement between Merchant and Buyer and for a reasonable period thereafter for purposes of collection. Information Sources may rely on this Permission without further verification or confirmation from Merchant. A photocopy, facsimile, or electronic image of this Permission shall be deemed equivalent to the original for all purposes.',
    section: 'authorisations',
    sortKey: 60,
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: ['ptr-section5-adds-purposes-not-granted'] }],
  },
  {
    slug: 'permission-to-release.release-of-information-sources',
    version: 1,
    instrument: 'permission-to-release',
    kind: 'clause',
    includeWhen: null,
    heading: 'Release of Information Sources',
    body: 'Merchant releases each Information Source, and each vendor, supplier, landlord/mortgagor, creditor and other person named in Section [[clause:permission-to-release.trade-landlord-and-bank-information]], from any and all liability arising from disclosures made in good-faith reliance on this Permission, including any claim for breach of confidentiality, invasion of privacy, or defamation. Merchant acknowledges that this release runs to the benefit of each Information Source as a third-party beneficiary.',
    section: 'authorisations',
    sortKey: 70,
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: ['ptr-release-misses-section1-sources'] }],
  },
  {
    slug: 'permission-to-release.personal-guarantor',
    version: 1,
    instrument: 'permission-to-release',
    kind: 'clause',
    includeWhen: null,
    heading: 'Personal Guarantor',
    body: 'The Personal Guarantor signs this Permission individually as well as on behalf of Merchant, and the authorizations in Sections [[clause:permission-to-release.credit-bureau-authorization]] and [[clause:permission-to-release.fair-credit-reporting-act-acknowledgment]] are given in that individual capacity. If no separate Personal Guarantor signs below, the person signing represents that they are the Personal Guarantor referred to in the Future Receivables Purchase Agreement.',
    section: 'authorisations',
    sortKey: 80,
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
  },
];
