import type { McaClause } from '../types';

/**
 * The Permission to Release — a preamble and seven numbered sections.
 *
 * PHASE 0 RECORDS THIS DOCUMENT AS HAVING ZERO CLAUSES. It has eight.
 *
 * Rewritten 2026-09-12 for transaction, report-use and signature boundaries.
 * The legacy source and review dispositions remain historical evidence, not
 * approval of these new bodies. All eight remain drafts at version 2. See
 * docs/research/mca-ancillary-consents-2026-09-12/README.md for authority and
 * execution/template follow-up, including the already-present r2 signature.
 */
export const PERMISSION_TO_RELEASE_SECTIONS: McaClause[] = [
  {
    slug: 'permission-to-release.preamble',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'load-bearing',
      note: 'The release needs the person signing, the business and Buyer identified; naming a funder profile does not establish the signer’s authority over another person’s information.',
    },
    version: 2,
    instrument: 'permission-to-release',
    kind: 'clause',
    unnumberedReason: 'Authorization lead-in identifying the person and merchant who give the following permissions.',
    includeWhen: null,
    heading: 'Persons and Transaction Identified',
    body: "I, ___________«1»___________, an authorized officer or owner of _____________«2»______________ (the “Merchant”), doing business as _____________«3»______________, with principal place of business at ______________________________«4»______________________________, sign on behalf of Merchant to give the business-information permissions below to ________«9»________ (“Buyer”). This Permission relates only to the particular application or Future Receivables Purchase Agreement supplied with it and identified before signature by Merchant's name, the transaction reference and the application or agreement date (the “Transaction”). Buyer shall identify those matters and provide this Permission in full before anyone signs; an unidentified transaction is not authorized.\nAn individual report subject gives only their own instructions by a separate individual signature as provided below. Signing for Merchant alone creates no personal guaranty and gives no authority over another individual's consumer report. Buyer's agents, servicers and permitted assigns receive no broader authority than Buyer and remain subject to the purposes, recipients and safeguards stated in this Permission.",
    section: 'authorisations',
    sortKey: 10,
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
  },
  {
    slug: 'permission-to-release.trade-landlord-and-bank-information',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'no-alternative',
      note: 'This business-information authorization has no authored alternative; commercial record access is a separate question from an individual consumer-report purpose.',
    },
    version: 2,
    instrument: 'permission-to-release',
    kind: 'clause',
    includeWhen: null,
    heading: 'Trade, Landlord, and Bank Information',
    body: "Merchant authorizes its vendors, suppliers, landlord, mortgage lender, banks, creditors, brokers and payment processors to disclose to Buyer business financial information reasonably necessary to underwrite the identified Transaction before the Purchase Date. After that date, a request must be reasonably necessary to service the FRPA, reconcile Purchased Receipts, or investigate a specific suspected diversion of Purchased Receipts. Each request shall state its purpose and be proportionate to it.\nThis Permission does not authorize a consumer report on an individual under the business-information grant. It does not authorize monitoring Merchant's continuing qualification for other programs or turn a decline in receipts or creditworthiness into a repayment duty, a default or a reason to suspend reconciliation. The FRPA's Financial Condition, Transaction History and Protection of Information provisions limit every request made in reliance on this Permission.",
    section: 'authorisations',
    sortKey: 20,
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
  },
  {
    slug: 'permission-to-release.banking-brokerage-and-processing-history',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'no-alternative',
      note: 'Business-record access is limited to the identified transaction and FRPA purposes; it does not supply authority for an individual consumer report or a transfer of funds.',
    },
    version: 2,
    instrument: 'permission-to-release',
    kind: 'clause',
    includeWhen: null,
    heading: 'Banking, Brokerage, and Processing History',
    body: "The business sources identified in Section [[clause:permission-to-release.trade-landlord-and-bank-information]], together with a commercial credit bureau lawfully holding Merchant's business information, are the “Information Sources.” Merchant authorizes them to provide Buyer the account balances and activity, processing volume, chargeback history, fees and commercial credit information reasonably necessary to underwrite the identified Transaction before the Purchase Date, and thereafter the account and processing history reasonably necessary to verify Purchased Receipts, reconcile them and service the FRPA lawfully. Each disclosure must be limited to the stated purpose.\nThis business-record permission does not authorize a consumer report on an individual. Describing financing as commercial does not remove the protections applicable to a consumer report, including a report on a sole proprietor. Section [[clause:permission-to-release.credit-bureau-authorization]] governs individual reports. This Permission authorizes no debit, withholding, transfer of funds, access to unrelated accounts or collection power beyond the FRPA.",
    section: 'authorisations',
    sortKey: 30,
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
  },
  {
    slug: 'permission-to-release.credit-bureau-authorization',
    whyThisClause: {
      kind: 'implements',
      citation: '15 U.S.C. §1681b(a)(2), (f) (individual consumer-report instructions and permissible use)',
    },
    variance: {
      kind: 'fixed',
      because: 'load-bearing',
      note: 'These individual instructions permit one initial underwriting report with a stated ending; a further report requires new specific instructions. This is the authored scope, not a claim that FCRA universally limits reports to one.',
    },
    version: 2,
    instrument: 'permission-to-release',
    kind: 'clause',
    includeWhen: null,
    heading: 'Individual Consumer-Report Instructions',
    body: "Only the individual who signs the separate individual authorization described in Section [[clause:permission-to-release.personal-guarantor]] gives the following instructions about their own report. That individual authorizes Buyer, as identified above, to obtain one consumer report solely to underwrite the identified Transaction before the Purchase Date. Buyer shall identify the consumer reporting agency to the individual before signature and retain the individual's signed and dated instructions with the transaction record. A business signature, an ownership interest or another person's guaranty does not supply those instructions.\nBuyer shall establish a separately documented permissible purpose under the Fair Credit Reporting Act and any authority state law requires before obtaining or using the report. These instructions authorize no recurring report, renewal report, continuing creditworthiness review, or report for servicing or collection. A further report requires new, specific individual instructions and its own documented lawful purpose, within the FRPA's limits. These instructions do not authorize an equipment provider, an unrelated affiliate or another funder to obtain a report.\nThe unused report permission ends when Buyer makes its initial financing decision, the application is declined or withdrawn, or the Purchase Date occurs, whichever happens first. The individual may revoke unused instructions prospectively by a reasonable communication received by Buyer. No statement here supplies a permissible purpose where the law does not.",
    section: 'authorisations',
    sortKey: 40,
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-01',
        findings: ['permission-guarantor-bound-without-signing', 'ptr-no-guarantor-signature-line'],
      },
      { review: 'REVIEW-02', findings: ['frpa-4-3-consumer-report-authority-depends-on-a-separate-instrument'] },
    ],
  },
  {
    slug: 'permission-to-release.fair-credit-reporting-act-acknowledgment',
    whyThisClause: {
      kind: 'implements',
      citation:
        '15 U.S.C. §§1681b(f), 1681m(a) (permissible consumer-report use and applicable adverse-action notices)',
    },
    variance: {
      kind: 'fixed',
      because: 'load-bearing',
      note: 'The release addresses permissible use and adverse-action obligations when consumer information is used; those duties do not disappear because report access was selected in a profile.',
    },
    version: 2,
    instrument: 'permission-to-release',
    kind: 'clause',
    includeWhen: null,
    heading: 'Consumer-Report Notices and Rights',
    body: "Buyer shall comply with the consumer-report use, accuracy, adverse-action and dispute duties applicable to it. If Buyer takes an adverse action with respect to an individual based in whole or in part on information in that individual's consumer report, Buyer shall give the notices required by FCRA §615(a) without waiting for a request. The notice shall identify the adverse action; give the name, address and telephone number of the consumer reporting agency, including its toll-free number where required; and explain that the agency did not make the decision and cannot give the specific reasons for it. It shall state the individual's right to request a free copy of the report from that agency within 60 days after receiving the notice and to dispute the accuracy or completeness of the report with the agency. If a numerical credit score was used, Buyer shall provide the written or electronic credit-score and related disclosures the law requires.\nA request for information about a report does not replace these automatic notice duties. Buyer shall provide any further notice or protection applicable law requires. Signing this Permission waives no consumer-report access, correction, dispute or other statutory right, and the business-information permissions do not substitute for the individual's instructions.",
    section: 'authorisations',
    sortKey: 50,
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-01',
        findings: [
          'permission-guarantor-bound-without-signing',
          'ptr-615a-rights-understated-as-upon-request',
          'ptr-no-guarantor-signature-line',
          'ptr-written-instructions-sourced-to-unsigned-frpa',
        ],
      },
      { review: 'REVIEW-02', findings: ['frpa-4-3-consumer-report-authority-depends-on-a-separate-instrument'] },
    ],
  },
  {
    slug: 'permission-to-release.continuing-authorization-reliance',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'no-alternative',
      note: 'The permissions end with their stated transaction or initial report purpose and may be revoked prospectively; lawful retention of existing records is not continuing authority for new access.',
    },
    version: 2,
    instrument: 'permission-to-release',
    kind: 'clause',
    includeWhen: null,
    heading: 'Duration, Revocation and Reliance',
    body: "The business-information permissions begin on Merchant's signature date. Before funding they end if the identified application is declined or withdrawn; after funding they end when the FRPA is completed or terminated. The individual report instructions have the earlier and narrower ending stated in Section [[clause:permission-to-release.credit-bureau-authorization]]. Neither permission continues for a different application, renewal or agreement.\nMerchant, or the individual for their own unused report instructions, may revoke the relevant permission prospectively by a reasonable communication received by Buyer. Buyer shall promptly communicate that revocation to an Information Source from which it has requested a pending disclosure and shall stop seeking new disclosures in reliance on the revoked permission. Revocation does not excuse Merchant's information duties under the FRPA; records may be supplied by another method that agreement permits. Revocation or loss of access does not by itself establish a default.\nBuyer may lawfully retain and use information already obtained only for its original permitted purpose, lawful enforcement or a legal retention requirement, subject to the FRPA's safeguards and applicable law. Retention does not authorize new access after a permission expires or is revoked. Information Sources may rely on a complete copy only within the authority actually given and subject to any revocation they receive; a copy does not dispense with verification required by law or the source's applicable security procedures.",
    section: 'authorisations',
    sortKey: 60,
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: ['ptr-section5-adds-purposes-not-granted'] }],
  },
  {
    slug: 'permission-to-release.release-of-information-sources',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'no-alternative',
      note: 'The authored provision limits recipients and preserves claims consistently with the FRPA. It grants no liability immunity; that allocation is a drafting choice, not prescribed FCRA wording.',
    },
    version: 2,
    instrument: 'permission-to-release',
    kind: 'clause',
    includeWhen: null,
    heading: 'Information Recipients, Safeguards and Preserved Rights',
    body: "Buyer may share only the minimum necessary information with a service provider or permitted assignee bound by confidentiality, security and purpose restrictions, or with an authority or reporting recipient as the FRPA and applicable law permit or require. Information Sources receive no authority under this Permission to disclose for another purpose. Buyer shall not sell account data or disclose it for unrelated marketing without separate lawful consent. The FRPA's Protection of Information provision governs safeguards, retention, deletion, incident notices and correction of inaccurate information; this Permission does not enlarge its permitted recipients or uses.\nThis Permission releases no claim for an inaccurate, unauthorized, negligent, malicious or unlawful disclosure or use, and waives no statutory privacy, consumer-report, access or dispute right. Good-faith reliance does not authorize an act outside the permission actually given. No Information Source acquires a collection right or a broader permission as a third-party beneficiary.",
    section: 'authorisations',
    sortKey: 70,
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: ['ptr-release-misses-section1-sources'] }],
  },
  {
    slug: 'permission-to-release.personal-guarantor',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'load-bearing',
      note: 'Business and individual report signatures identify different capacities. Neither creates a guaranty; a missing individual signature cannot be replaced by deeming the merchant representative a guarantor.',
    },
    version: 2,
    instrument: 'permission-to-release',
    kind: 'clause',
    includeWhen: null,
    heading: 'Signature Capacities; No Guaranty',
    body: "The authorized representative signs only on behalf of Merchant in the Merchant signature block. Only a person who gives a separate individual signature in the individual authorization block gives the instructions about that person's own consumer report under Section [[clause:permission-to-release.credit-bureau-authorization]]. Before that individual signs, Buyer shall identify the individual, Buyer, the Transaction, the reporting agency, the underwriting purpose and the permission's ending, and shall provide the complete Permission. An absent, unsigned or incomplete individual authorization grants no report permission for that individual. One individual cannot sign for another individual under this Permission.\nA person who acts in both capacities must sign separately in each capacity. Signing this Permission in either capacity creates no personal guaranty, adopts no guaranty in another document and creates no duty to pay Merchant's obligations. A guaranty, if any, must be separately and expressly agreed in its own instrument. Buyer shall retain the completed Permission and provide a copy to each signer.",
    section: 'authorisations',
    sortKey: 80,
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
  },
];
