import type { McaClause } from '../types';

/**
 * Appendix A and the exhibits — fees, execution, and the instruments this one calls for.
 *
 * Bodies are the words the shipped document prints.
 * `__tests__/frpa-coverage.test.ts` additionally asserts that NOTHING in the
 * document is missing from the library — the direction that fails silently.
 */
export const FRPA_APPENDIX: McaClause[] = [
  {
    slug: 'frpa.appendix-a-fees-collectible',
    version: 1,
    instruments: ['frpa'],
    number: 'Appendix A',
    section: 'appendix',
    sortKey: 10,
    heading: '',
    body: 'All fees are added to the Remaining Balance and are collectible via the same methods as the Purchased Amount. Fees may be voided by Buyer in its discretion, but voided fees remain on record for audit purposes.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
  },
  {
    slug: 'frpa.appendix-a-origination-fee-to-iso',
    version: 1,
    instruments: ['frpa'],
    number: 'Appendix A',
    section: 'appendix',
    sortKey: 20,
    heading: '',
    body: 'Some or all of the Origination Fee may be paid to an independent sales organization (“ISO”). Otherwise, Buyer is NOT charging any ISO fees to Merchant. If Merchant is charged another such fee, Merchant acknowledges that it is not being charged by Buyer.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
  },
  {
    slug: 'frpa.appendix-a-attorneys-fees',
    version: 1,
    instruments: ['frpa'],
    number: 'Appendix A',
    section: 'appendix',
    sortKey: 30,
    heading: '',
    body: 'Attorneys’ Fees / Collection Fees: Buyer may recover its attorneys’ fees and collection fees actually incurred and reasonable in amount. These are not calculated as a percentage of the undelivered Purchased Amount, and together with every other enforcement cost recoverable under this Agreement they are subject to the aggregate limit in Section 6.3.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
  },
  {
    slug: 'frpa.execution',
    version: 1,
    instruments: ['frpa'],
    number: '',
    section: 'appendix',
    sortKey: 40,
    heading: '',
    body: 'IN WITNESS WHEREOF, the parties have executed this Agreement as of the Effective Date. Each of Merchant and Guarantor represents that he or she is authorized to sign this Agreement, legally binding Merchant and Guarantor to comply with the terms of this Agreement and that the information provided herein and in all of Buyer’s documents, forms, and recorded interviews is true, accurate, and complete in all respects. Any misrepresentation made by Merchant or Guarantor in connection with this Agreement may constitute a separate cause of action for fraud or intentional misrepresentation.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
  },
  {
    slug: 'frpa.exhibit-a-split-funding',
    version: 1,
    instruments: ['frpa'],
    number: 'Exhibit A',
    section: 'appendix',
    sortKey: 50,
    heading: '',
    body: 'A separate Split Funding Authorization Letter shall be executed for each Approved Processor identified in Section 1.5, instructing the Approved Processor to remit the Specified Percentage of credit and debit card receipts directly to Buyer’s designated account. The form of the Split Funding Authorization is attached and incorporated by reference, and shall be executed contemporaneously with this Agreement.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
  },
  {
    slug: 'frpa.exhibit-c-permission-to-release',
    version: 1,
    instruments: ['frpa'],
    number: 'Exhibit C',
    section: 'appendix',
    sortKey: 60,
    heading: '',
    body: 'A Permission to Release Information shall be executed by Merchant as a separate signed instrument authorizing Buyer to obtain trade, landlord, and bank information from vendors, suppliers, landlord/mortgagor, banks, creditors, brokers, and payment processors for the purposes of underwriting, ongoing program qualification, and post-default collection. The form of the Permission to Release Information is attached and incorporated by reference, and shall be executed contemporaneously with this Agreement.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
  },
];
