import type { McaClause } from '../types';

/**
 * Section 4 — terms of enrollment.
 *
 * Bodies are the words the shipped document prints.
 * `__tests__/frpa-coverage.test.ts` additionally asserts that NOTHING in the
 * document is missing from the library — the direction that fails silently.
 */
export const FRPA_ENROLLMENT: McaClause[] = [
  {
    slug: 'frpa.merchant-deposit-agreement-4-1',
    version: 1,
    instrument: 'frpa',
    number: '4.1',
    section: 'enrollment',
    sortKey: 10,
    heading: 'Merchant Deposit Agreement',
    body: 'Merchant shall execute an agreement (the “Merchant Deposit Agreement”) acceptable to Buyer and have the Approved Bank Account with a depository institution (“Bank”) acceptable to Buyer. Merchant shall provide Buyer and/or its authorized agent with the information and authorizations necessary to verify Merchant’s Receipts into the Approved Bank Account.\nMerchant authorizes its merchant processor and applicable third parties to provide Buyer all information necessary to permit Buyer to determine the Specified Percentage due.\nBuyer may charge fees as set forth on Appendix A (the “Fee Structure”); such fees are added to the Remaining Balance and collected through the same settlement remittance as the Purchased Amount. Every amount deducted from the Purchase Price before delivery to Merchant must appear as a line in the itemization in Section 1.4 and be stated as a dollar figure before Merchant signs. Buyer may not deduct any amount that does not so appear.\nThe foregoing authorizations shall continue in effect until Buyer receives final payment of the entire Purchased Amount and all other amounts due. Bank may rely upon the instructions of Buyer without independent verification. Merchant waives any claim for damages against Bank in connection with actions taken based upon instructions from Buyer, unless such damages were due to Bank’s failure to follow Buyer’s instructions.\nMerchant acknowledges that: (i) Bank will be acting on behalf of Buyer with respect to portions of the Purchased Amount until remitted to Buyer through the settlement process; (ii) Bank may or may not be an affiliate of Buyer; (iii) Merchant has no power or authority to control Bank’s or Buyer’s actions with respect to remittance; (iv) Buyer is not responsible and shall not be liable for the actions of Bank, and Merchant agrees to hold Buyer harmless; and (v) funds representing the Purchased Amount in the possession of Bank and Buyer constitute property owned solely by Buyer, and Merchant disclaims any and all interest therein.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-01',
        findings: [
          'amount-you-deliver-is-not-fixed',
          'closing-costs-undefined-and-unbounded',
          'completion-threshold-two-conflicting-tests',
          'defined-term-drift',
          'frpa-undefined-capitalised-terms',
          'undefined-money-terms',
        ],
      },
    ],
  },
  {
    slug: 'frpa.term-of-agreement-4-2',
    version: 1,
    instrument: 'frpa',
    number: '4.2',
    section: 'enrollment',
    sortKey: 20,
    heading: 'Term of Agreement',
    body: 'This Agreement shall continue until the Completion Threshold is attained (Section 2.6).',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-01',
        findings: ['acceleration-defeats-indefinite-term', 'completion-threshold-two-conflicting-tests'],
      },
      { review: 'REVIEW-02', findings: ['frpa-7-6-and-4-2-contradict-the-2-6-completion-test'] },
    ],
  },
  {
    slug: 'frpa.financial-condition-4-3',
    version: 1,
    instrument: 'frpa',
    number: '4.3',
    section: 'enrollment',
    sortKey: 30,
    heading: 'Financial Condition',
    body: 'Merchant and Guarantor(s) authorize Buyer and its agents to investigate their financial responsibility and history and shall provide to Buyer any bank or financial statements, tax returns, and other financial documentation as Buyer deems necessary prior to or at any time after execution of this Agreement. A photocopy of this authorization will be deemed acceptable for release of financial information. Buyer is authorized to update such information and financial profiles from time to time as it deems appropriate.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      { review: 'REVIEW-02', findings: ['frpa-4-3-consumer-report-authority-depends-on-a-separate-instrument'] },
    ],
  },
  {
    slug: 'frpa.transaction-history-4-4',
    version: 1,
    instrument: 'frpa',
    number: '4.4',
    section: 'enrollment',
    sortKey: 40,
    heading: 'Transaction History',
    body: 'Merchant authorizes the Bank and the Approved Processor to provide Buyer with Merchant’s banking and credit-card processing history from time to time to determine qualification or continuation in this program.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: ['frpa-undefined-capitalised-terms-in-the-unexamined-clauses'] }],
  },
  {
    slug: 'frpa.no-liability-4-5',
    version: 1,
    instrument: 'frpa',
    number: '4.5',
    section: 'enrollment',
    sortKey: 50,
    heading: 'No Liability',
    body: 'In no event will Buyer be liable for any claims asserted by Merchant or Guarantors under any legal theory for lost profits, lost revenues, lost business opportunities, exemplary, punitive, special, incidental, indirect or consequential damages, each of which is waived by Merchant and Guarantor(s).',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-02',
        findings: [
          'el-4-5-fcra-authorisation-runs-to-a-different-entity-than-the-frpas',
          'frpa-4-5-exculpation-is-unqualified-where-every-sibling-clause-is-qualified',
        ],
      },
    ],
  },
  {
    slug: 'frpa.power-of-attorney-4-6',
    version: 1,
    instrument: 'frpa',
    number: '4.6',
    section: 'enrollment',
    sortKey: 60,
    heading: 'Power of Attorney',
    body: 'Merchant irrevocably appoints Buyer as its agent and attorney-in-fact with full authority to take any action or execute any instrument or document in the case of a violation by Merchant of any term of this Agreement or the occurrence of an Event of Default, including without limitation: (i) to obtain and adjust insurance; (ii) to collect monies due or to become due under or in respect of any of the Collateral; (iii) to receive, endorse and collect any checks, notes, drafts, instruments, documents or chattel paper in connection with clauses (i) or (ii) above; (iv) to sign Merchant’s name on any invoice, bill of lading, or assignment directing customers or account debtors to make payment directly to Buyer; and (v) to file any claims or take any action or institute any proceeding which Buyer may deem necessary for the collection of any of the unpaid Purchased Amount from the Collateral, or otherwise to enforce its rights with respect to payment of the Purchased Amount.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
  },
  {
    slug: 'frpa.protection-of-information-4-7',
    version: 1,
    instrument: 'frpa',
    number: '4.7',
    section: 'enrollment',
    sortKey: 70,
    heading: 'Protection of Information',
    body: 'Merchant and each person signing this Agreement on behalf of Merchant and/or as Guarantor authorizes Buyer to disclose information concerning Merchant’s and each Guarantor’s credit standing and business conduct only to agents, affiliates, subsidiaries, and credit reporting bureaus as is required in connection with the Receipts. Merchant and Guarantor(s) waive to the maximum extent permitted by law any claim for damages against Buyer or any of its affiliates relating to any (i) investigation undertaken by or on behalf of Buyer as permitted by this Agreement, or (ii) disclosure of information as permitted by this Agreement.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: ['information-sharing-only-vs-any-third-party'] }],
  },
  {
    slug: 'frpa.confidentiality-4-8',
    version: 1,
    instrument: 'frpa',
    number: '4.8',
    section: 'enrollment',
    sortKey: 80,
    heading: 'Confidentiality',
    body: 'Merchant agrees that the terms and conditions of the products and services offered by Buyer, including this Agreement and any other Buyer documentation (collectively, “Confidential Information”), are proprietary and confidential information of Buyer. Unless disclosure is required by law or court order, Merchant shall not disclose Confidential Information to any person other than Merchant’s attorney, accountant, financial advisor, or employee who needs to know such information for the purpose of advising Merchant (each, an “Advisor”), provided such Advisor uses such information solely for advising Merchant and first agrees in writing to be bound by the terms of this Section. Notwithstanding that proviso, Merchant may disclose Confidential Information to its attorney, accountant or other professional adviser for the purpose of advising Merchant without that adviser giving any undertaking to Buyer, and may disclose Confidential Information to any governmental or regulatory authority. Confidential Information does not include information that is or becomes public other than through a breach of this Section.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-02',
        findings: [
          'frpa-4-8-conditions-the-counsel-review-7-22-promises',
          'frpa-4-8-may-impede-a-merchant-complaint-to-a-regulator',
        ],
      },
    ],
  },
  {
    slug: 'frpa.d-b-a-names-4-9',
    version: 1,
    instrument: 'frpa',
    number: '4.9',
    section: 'enrollment',
    sortKey: 90,
    heading: 'D/B/A Names',
    body: 'Merchant acknowledges that Buyer may use “doing business as” or “d/b/a” names in connection with various matters relating to the transaction, including the filing of UCC-1 financing statements and other notices or filings.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      { review: 'REVIEW-02', findings: ['frpa-4-9-authorises-ucc-filings-under-a-dba-the-repository-does-not-record'] },
    ],
  },
  {
    slug: 'frpa.security-interest-4-10',
    version: 1,
    instrument: 'frpa',
    number: '4.10',
    section: 'enrollment',
    sortKey: 100,
    heading: 'Security Interest',
    body: 'To secure Merchant’s payment and performance obligations under this Agreement, Merchant hereby grants Buyer a security interest in: (a) the Receipts purchased under this Agreement and the accounts and other receivables from which those Receipts arise, as those terms are defined by Article 9 of the Uniform Commercial Code (the “UCC”); and (b) all identifiable proceeds of the foregoing, as defined by Article 9 of the UCC, including identifiable proceeds on deposit in the Approved Bank Account (collectively, the “Collateral”). This security interest is precautionary and is limited to the purchased Receipts and their proceeds. It does not extend to Merchant’s equipment, inventory, chattel paper, documents, instruments or general intangibles, and Buyer shall not file any financing statement purporting to reach them.\nMerchant and Guarantor each agree to execute any documents or take any action Buyer deems necessary to perfect or maintain Buyer’s first-priority security interest in the Collateral, including the execution of any account control agreements. Merchant and Guarantor authorize Buyer to file any financing statements deemed necessary by Buyer. Merchant and Guarantor shall be liable for, and Buyer may charge and collect, the reasonable costs and expenses, including reasonable attorneys’ fees, actually incurred by Buyer in protecting, preserving, and enforcing Buyer’s security interest, subject to the aggregate limit in Section 6.3. Buyer may use another legal name or D/B/A when designating the Secured Party in such filings.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-01',
        findings: [
          'all-assets-lien-vs-nonrecourse-recital',
          'charges-scattered-outside-fee-schedule',
          'frpa-sub-equipment-lien-conflict',
          'liquidated-damages-plus-actual-costs',
          'three-inconsistent-attorney-fee-formulas',
        ],
      },
      { review: 'REVIEW-02', findings: ['frpa-4-9-authorises-ucc-filings-under-a-dba-the-repository-does-not-record'] },
    ],
  },
  {
    slug: 'frpa.negative-pledge-4-11',
    version: 1,
    instrument: 'frpa',
    number: '4.11',
    section: 'enrollment',
    sortKey: 110,
    heading: 'Negative Pledge',
    body: 'Merchant and Guarantor each agrees not to create, incur, assume, or permit to exist, directly or indirectly, any lien on or with respect to any of the Collateral other than the security interest granted to Buyer and the monthly Equipment payment billed at merchant level by the Approved Processor under an Equipment Lease Agreement between Merchant and Lombard Pay LLC, which is a permitted claim ranking after the Specified Percentage. This Section does not restrict Merchant from granting a lien on any asset that is not Collateral.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      { review: 'REVIEW-01', findings: ['all-assets-lien-vs-nonrecourse-recital', 'frpa-sub-equipment-lien-conflict'] },
    ],
  },
  {
    slug: 'frpa.remedies-4-12',
    version: 1,
    instrument: 'frpa',
    number: '4.12',
    section: 'enrollment',
    sortKey: 120,
    heading: 'Remedies',
    body: 'Upon any Event of Default, Buyer may pursue any remedy available at law (including those available under the UCC) or in equity to collect, enforce, or satisfy any obligations then owing, subject in every case to the limits in Section 6 — including the restriction in Section 6.2 on the availability of the remedy in Section 6.2.1, the notice and cure requirement in Section 6.1, and the aggregate limit in Section 6.3.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: ['frpa-4-12-reopens-the-acceleration-6-2-closed'] }],
  },
  {
    slug: 'frpa.timing-and-method-of-funding-4-13',
    version: 1,
    instrument: 'frpa',
    number: '4.13',
    section: 'enrollment',
    sortKey: 130,
    heading: 'Timing and Method of Funding',
    body: 'Merchant and Buyer agree that Buyer shall purchase the Receipts on a date to be determined by Buyer in its sole discretion (the “Purchase Date”). Buyer, in its sole discretion, may refuse to purchase the Receipts for any reason or no reason. Buyer shall provide payment through any commercially reasonable method, at Buyer’s sole discretion, including check, federal funds wire, or ACH transfer.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-02',
        findings: [
          'frpa-4-13-unlimited-right-to-refuse-vs-ct-offer-revocation-bar',
          'frpa-undefined-capitalised-terms-in-the-unexamined-clauses',
        ],
      },
    ],
  },
  {
    slug: 'frpa.right-to-cancel-4-14',
    version: 1,
    instrument: 'frpa',
    number: '4.14',
    section: 'enrollment',
    sortKey: 140,
    heading: 'Right to Cancel',
    body: 'Merchant has the right to cancel this Agreement within three (3) calendar days after Buyer has delivered the Net Amount Funded. Merchant may exercise this right by notifying Buyer in writing that it is cancelling this Agreement and returning the Net Amount Funded to Buyer, including any payoffs made on Merchant’s behalf by Buyer. For the cancellation to be effective, Buyer must receive both the notice and the return of the funds within three (3) calendar days after Buyer has delivered the Net Amount Funded.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      { review: 'REVIEW-01', findings: ['cancellation-forfeits-origination-fee'] },
      { review: 'REVIEW-02', findings: ['iso-a2-a4-no-clawback-when-the-merchant-cancels-under-frpa-4-14'] },
    ],
  },
  {
    slug: 'frpa.position-and-cascade-of-collections-4-15',
    version: 1,
    instrument: 'frpa',
    number: '4.15',
    section: 'enrollment',
    sortKey: 150,
    heading: 'Position and Cascade of Collections',
    body: 'If Merchant has multiple active funding agreements with Buyer (each a “Position”), collections of the Specified Percentage and Estimated Daily Holdback shall be applied to the lowest-numbered Position first (Position 1 being the first-priority funding). Upon completion of any Position (i.e., upon attainment of the Completion Threshold for that Position), collections shall automatically cascade to the next active Position in ascending order. The provisions of this Section 4.15 supplement (and do not waive) the prohibition on third-party Stacking under Section 5.16; this Section governs only Buyer’s own multi-position fundings on the same Merchant.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: ['lombard-multi-position-vs-no-stack'] }],
  },
  {
    slug: 'frpa.electronic-account-monitoring-authorization-plaid-4-16',
    version: 1,
    instrument: 'frpa',
    number: '4.16',
    section: 'enrollment',
    sortKey: 160,
    heading: 'Electronic Account Monitoring Authorization (Plaid)',
    body: "Merchant authorizes Buyer to obtain read-only electronic access to the Approved Bank Account through Plaid, Inc. (or any equivalent secure bank-data aggregation service designated by Buyer) for the purpose of (a) verifying Merchant's daily and weekly Receipts during the term of this Agreement, (b) supporting the Reconciliation procedures set forth in Section 3, (c) confirming that the Specified Percentage of Receipts is being properly remitted by the Approved Processor, and (d) ongoing creditworthiness review by Buyer.\nMerchant shall (i) authorize the Plaid connection during onboarding, (ii) maintain the connection in active status throughout the term of this Agreement, and (iii) promptly re-authorize if the connection lapses for any reason (including bank-side credential changes or token expiry). Buyer's access via Plaid is read-only; this authorization does not, by itself, authorize any debit, transfer, or withdrawal — collection mechanisms are governed exclusively by Section 2.3 (Split Funding via Approved Processor).\nMerchant acknowledges that prolonged loss of Plaid connectivity (more than five (5) consecutive Workdays without Buyer's prior written consent) shall constitute an Event of Default under Section 6.1.1, except that a lapse arising from a cause outside Merchant's reasonable control — including a bank-side credential change, token expiry, or an outage at the aggregation service — shall not be an Event of Default if Merchant re-authorizes the connection within ten (10) Workdays after notice from Buyer.\nBuyer agrees to (i) handle all data obtained through Plaid in accordance with applicable privacy and data-protection laws, (ii) limit access to essential personnel only, and (iii) not share Merchant's bank-data with third parties except as required for servicing this Agreement (e.g., the Approved Processor or industry-standard performance reporting per Section 7.15).",
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-01',
        findings: [
          'defined-term-drift',
          'frpa-plaid-default-not-enumerated-in-61',
          'guaranty-covers-every-covenant',
          'no-cure-period-anywhere',
          'plaid-connectivity-lapse-is-default',
          'plaid-lapse-is-strict-liability-default',
        ],
      },
    ],
  },
];
