import type { McaClause } from '../types';

/**
 * Sections 7 and 8 — miscellaneous, renewal and rollover.
 *
 * Bodies are the words the shipped document prints.
 * `__tests__/frpa-coverage.test.ts` additionally asserts that NOTHING in the
 * document is missing from the library — the direction that fails silently.
 */
export const FRPA_MISCELLANEOUS: McaClause[] = [
  {
    slug: 'frpa.modifications-amendments-7-1',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    includeWhen: null,
    number: '7.1',
    section: 'miscellaneous',
    sortKey: 10,
    heading: 'Modifications; Amendments',
    body: 'Except as expressly provided in Sections 3.3, 3.4 and 4.15, no modification, amendment, waiver, or consent of any provision of this Agreement shall be effective unless the same shall be in writing and signed by both parties.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: ['frpa-7-1-has-no-except-as-expressly-provided-carve-out'] }],
  },
  {
    slug: 'frpa.assignment-7-2',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    includeWhen: null,
    number: '7.2',
    section: 'miscellaneous',
    sortKey: 20,
    heading: 'Assignment',
    body: 'Buyer may assign, transfer, or sell its rights to receive the Purchased Amount or delegate its duties hereunder, either in whole or in part. Merchant may not assign this Agreement without Buyer’s prior written consent, which consent may be withheld in Buyer’s sole discretion.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: ['frpa-7-2-permits-delegation-of-the-reconciliation-duty'] }],
  },
  {
    slug: 'frpa.notices-7-3',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    includeWhen: null,
    number: '7.3',
    section: 'miscellaneous',
    sortKey: 30,
    heading: 'Notices',
    body: 'All notices, requests, consents, demands, and other communications hereunder shall be delivered by certified mail, return receipt requested, to the respective parties at the addresses set forth in this Agreement (or at such other address as the party shall specify in writing) and shall become effective only upon receipt.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      { review: 'REVIEW-01', findings: ['reconciliation-right-conditioned-into-near-nullity'] },
      { review: 'REVIEW-02', findings: ['frpa-6-4-24-hour-notice-cannot-be-given-under-7-3'] },
    ],
  },
  {
    slug: 'frpa.waiver-of-remedies-7-4',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    includeWhen: null,
    number: '7.4',
    section: 'miscellaneous',
    sortKey: 40,
    heading: 'Waiver of Remedies',
    body: 'No failure on the part of Buyer to exercise, and no delay in exercising, any right under this Agreement shall operate as a waiver thereof, nor shall any single or partial exercise of any right under this Agreement preclude any other or further exercise thereof or the exercise of any other right. The remedies provided hereunder are cumulative and not exclusive of any remedies provided by law or equity.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
  },
  {
    slug: 'frpa.binding-effect-governing-law-venue-and-jurisdiction-7-5',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    includeWhen: null,
    number: '7.5',
    section: 'miscellaneous',
    sortKey: 50,
    heading: 'Binding Effect; Governing Law, Venue, and Jurisdiction',
    body: 'This Agreement shall be binding upon and inure to the benefit of the parties and their respective successors and assigns, except that Merchant shall not have the right to assign its rights hereunder or any interest herein without the prior written consent of Buyer, which consent may be withheld in Buyer’s sole discretion. This Agreement shall be governed by and construed in accordance with the laws of the State of New York. This Agreement is for the sale of Merchant’s future Receipts and is subject to the Uniform Commercial Code as adopted in New York. Any suit, action, or proceeding arising hereunder, or the interpretation, performance, or breach hereof, shall, if Buyer so elects, be instituted in any court sitting in New York State or in Pasco County, Florida (the “Acceptable Forums”). The parties agree that the Acceptable Forums are convenient and submit to the jurisdiction of the Acceptable Forums and waive any and all objections to jurisdiction or venue. Should a proceeding be initiated in any other forum, the parties waive any right to oppose any motion or application made by either party to transfer such proceeding to an Acceptable Forum. Merchant and Guarantor(s) further agree that mailing by certified or registered mail, return receipt requested, of any process required by any such court will constitute valid and lawful service of process against them, without the necessity for service by any other means.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-01',
        findings: [
          'counterclaim-waiver-flips-by-forum',
          'frpa-arbitration-clauses-with-no-arbitration-agreement',
          'ny-law-below-gol-5-1401-threshold',
        ],
      },
      { review: 'REVIEW-02', findings: ['frpa-7-24-does-not-name-the-statute-that-actually-bites'] },
    ],
  },
  {
    slug: 'frpa.survival-of-representations-7-6',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    includeWhen: null,
    number: '7.6',
    section: 'miscellaneous',
    sortKey: 60,
    heading: 'Survival of Representations',
    body: 'All representations, warranties, and covenants herein shall survive the execution and delivery of this Agreement and shall continue in full force until the Completion Threshold is attained and all amounts then due have been paid.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: ['frpa-7-6-and-4-2-contradict-the-2-6-completion-test'] }],
  },
  {
    slug: 'frpa.severability-7-7',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    includeWhen: null,
    number: '7.7',
    section: 'miscellaneous',
    sortKey: 70,
    heading: 'Severability',
    body: 'In case any of the provisions in this Agreement is found to be invalid, illegal, or unenforceable in any respect, the validity, legality, and enforceability of any other provision contained herein shall not in any way be affected or impaired. Any provision hereof prohibited by law shall be ineffective only to the extent of such prohibition without invalidating the remaining provisions hereof.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: ['frpa-severability-text-under-entire-agreement'] }],
  },
  {
    slug: 'frpa.entire-agreement-7-8',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    includeWhen: null,
    number: '7.8',
    section: 'miscellaneous',
    sortKey: 80,
    heading: 'Entire Agreement',
    body: 'This Agreement embodies the entire agreement between Merchant and Buyer and supersedes all prior agreements and understandings relating to the subject matter hereof.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: ['frpa-severability-text-under-entire-agreement'] }],
  },
  {
    slug: 'frpa.indemnification-7-9',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    includeWhen: null,
    number: '7.9',
    section: 'miscellaneous',
    sortKey: 90,
    heading: 'Indemnification',
    body: 'Upon the occurrence of any Event of Default, Merchant and Guarantor(s) jointly and severally shall assume liability for and hereby agree to indemnify, protect, and keep harmless Buyer and any third-party servicers from and against any and all liabilities, claims, losses, obligations, damages, penalties, actions, and suits of whatsoever kind and nature imposed on, incurred by, or asserted against Buyer or any third-party servicers in any way relating to or arising out of such Event of Default (collectively, “Indemnified Amounts”), including, subject to the aggregate limit in Section 6.3, the payment of costs and expenses reasonably incurred for the enforcement of Buyer’s rights and remedies hereunder, including the collection of amounts due to Buyer hereunder and attorneys’ fees and costs in any trial court or appellate court proceeding or administrative proceeding, or any negotiations or consultations, in connection with any Event of Default. Such Indemnified Amounts shall accrue at the rate set forth in Section 6.3.1, from the date of demand until paid in full.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-01',
        findings: [
          'charges-scattered-outside-fee-schedule',
          'frpa-arbitration-clauses-with-no-arbitration-agreement',
          'indemnity-charges-interest-document-denies',
          'interest-charges-inside-a-not-a-loan',
          'liquidated-damages-plus-actual-costs',
          'orphan-arbitration-references',
          'orphan-arbitration-twenty-day-bar',
          'three-inconsistent-attorney-fee-formulas',
        ],
      },
    ],
  },
  {
    slug: 'frpa.jury-trial-waiver-7-10',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    /*
      One of four clauses the memo proposes deleting separately; they are one fact.
      A jury waiver is meaningless under an arbitration template.
    */
    includeWhen: (facts) => facts.disputeResolution === 'courts',
    number: '7.10',
    section: 'miscellaneous',
    sortKey: 100,
    heading: 'Jury Trial Waiver',
    body: 'THE PARTIES HERETO WAIVE TRIAL BY JURY IN ANY COURT IN ANY SUIT, ACTION, OR PROCEEDING ON ANY MATTER ARISING IN CONNECTION WITH OR IN ANY WAY RELATED TO THE TRANSACTIONS OF WHICH THIS AGREEMENT IS A PART OR THE ENFORCEMENT HEREOF. THE PARTIES HERETO ACKNOWLEDGE THAT EACH MAKES THIS WAIVER KNOWINGLY, WILLINGLY, AND VOLUNTARILY AND WITHOUT DURESS, AND ONLY AFTER EXTENSIVE CONSIDERATION OF THE RAMIFICATIONS OF THIS WAIVER WITH THEIR ATTORNEYS.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: ['frpa-7-10-jury-waiver-recites-what-7-22-contemplates-is-false'] }],
  },
  {
    slug: 'frpa.class-action-waiver-7-11',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    /*
      All three market forms pair a class waiver WITH arbitration. A bare one, as
      here, is the weakest of the three positions — but that is a drafting
      question, not a reason to exclude it from a courts template.
    */
    includeWhen: (facts) => facts.disputeResolution === 'courts',
    number: '7.11',
    section: 'miscellaneous',
    sortKey: 110,
    heading: 'Class Action Waiver',
    body: 'THE PARTIES HERETO WAIVE ANY RIGHT TO ASSERT ANY CLAIMS AGAINST THE OTHER PARTY, AS A REPRESENTATIVE OR MEMBER IN ANY CLASS OR REPRESENTATIVE ACTION, EXCEPT WHERE SUCH WAIVER IS PROHIBITED BY LAW OR AGAINST PUBLIC POLICY.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: ['class-waiver-forfeits-own-recovery'] }],
  },
  {
    slug: 'frpa.service-of-process-7-12',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    includeWhen: null,
    number: '7.12',
    section: 'miscellaneous',
    sortKey: 120,
    heading: 'Service of Process',
    body: 'IN ADDITION TO THE METHODS OF SERVICE ALLOWED BY STATE LAW, MERCHANT HEREBY CONSENTS TO SERVICE OF PROCESS UPON IT BY REGISTERED OR CERTIFIED MAIL, RETURN RECEIPT REQUESTED. SERVICE HEREUNDER SHALL BE COMPLETE UPON MERCHANT’S ACTUAL RECEIPT OF PROCESS OR UPON BUYER’S RECEIPT OF THE RETURN THEREOF BY THE UNITED STATES POSTAL SERVICE AS REFUSED OR UNDELIVERABLE. MERCHANT MUST PROMPTLY NOTIFY BUYER, IN WRITING, OF EACH AND EVERY CHANGE OF ADDRESS TO WHICH SERVICE OF PROCESS CAN BE MADE. SERVICE BY BUYER TO THE LAST KNOWN ADDRESS SHALL BE SUFFICIENT. MERCHANT WILL HAVE THIRTY (30) CALENDAR DAYS AFTER SERVICE HEREUNDER IS COMPLETE IN WHICH TO RESPOND. THE PARTIES FURTHER AGREE TO ACCEPT SERVICE OF PROCESS BY EMAIL TO ANY EMAILS DESIGNATED IN THIS AGREEMENT.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      { review: 'REVIEW-01', findings: ['ct-prejudgment-remedy-waiver', 'service-without-notice-vs-commitment-9'] },
    ],
  },
  {
    slug: 'frpa.sale-of-additional-pool-of-receipts-right-of-first-refusal-7-13',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    /*
      Master-agreement treatment and the ROFR are renewal machinery.
    */
    includeWhen: (facts) => facts.renewalModel !== 'none',
    number: '7.13',
    section: 'miscellaneous',
    sortKey: 130,
    heading: 'Sale of Additional Pool of Receipts; Right of First Refusal',
    body: 'In the event that Merchant wishes to sell, and Buyer agrees to purchase, an additional pool (or additional pools) of Receipts, this Agreement shall serve as a Master Agreement which sets forth all of the terms and conditions governing any such sale. The parties shall execute an additional schedule for each such purchase, setting forth the Purchase Price, Specified Percentage, Estimated Daily Holdback, and Purchased Amount applicable to that additional pool of future receivables. The Purchase Price listed on such schedule shall be reduced dollar-for-dollar by Purchased Amounts then outstanding from prior purchases of Receipts by Buyer. Nothing herein shall obligate either party to sell and purchase additional pools; however, Merchant grants Buyer the right of first refusal to purchase any such pool of additional future receivables that Merchant may wish to sell.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      { review: 'REVIEW-01', findings: ['frontload-refactors-old-balance', 'lombard-multi-position-vs-no-stack'] },
    ],
  },
  {
    slug: 'frpa.reporting-7-15',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    includeWhen: null,
    number: '7.15',
    section: 'miscellaneous',
    sortKey: 150,
    heading: 'Reporting',
    body: 'Buyer and its affiliates are or may become members of one or more industry associations that exchange and share information regarding the performance by merchants under merchant cash advance and related documents. Buyer and its affiliates reserve the right, without further notice to Merchant, to provide information to such industry associations relating to Merchant and its principals, as well as Merchant’s performance under this Agreement and related documents. Merchant, for itself and its principals, authorizes Buyer and its affiliates to provide such information without further notice to or consent of Merchant or its principals.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: ['information-sharing-only-vs-any-third-party'] }],
  },
  {
    slug: 'frpa.return-of-buyer-proceeds-7-16',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    includeWhen: null,
    number: '7.16',
    section: 'miscellaneous',
    sortKey: 160,
    heading: 'Return of Buyer Proceeds',
    body: 'In the event that Merchant, or any of Merchant’s respective directors, officers, employees, agents, subcontractors, or affiliates receives or comes into possession of any proceeds of the Purchased Amount, Merchant shall, or shall cause such other recipients to, immediately segregate and hold such proceeds in express trust for Buyer’s sole and exclusive benefit. Such proceeds shall be delivered to Buyer in full within three (3) business days of such receipt.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: ['default-collection-reaches-cash-and-checks'] }],
  },
  {
    slug: 'frpa.electronic-signatures-7-17',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    includeWhen: null,
    number: '7.17',
    section: 'miscellaneous',
    sortKey: 170,
    heading: 'Electronic Signatures',
    body: 'Electronic signatures (including those executed via any commercially recognized electronic-signature platform) shall be deemed acceptable for all purposes and shall have the same force and effect as original ink signatures. Electronic copies of this Agreement shall be treated as originals for all purposes.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
  },
  {
    slug: 'frpa.communications-recording-and-premises-access-7-18',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    includeWhen: null,
    number: '7.18',
    section: 'miscellaneous',
    sortKey: 180,
    heading: 'Communications, Recording, and Premises Access',
    body: "Buyer may monitor and/or record any telephone call between Buyer and any Merchant or Guarantor, or any of their respective owners, employees, or agents. By signing this Agreement, each Merchant and Guarantor agrees that any such call may be monitored and/or recorded.\nEach Merchant and Guarantor expressly consents and authorizes Buyer, its servicers, and their respective subsidiaries and affiliates to call, send text messages, and/or send other electronic messages (including prerecorded or artificial voice messages) using an automatic telephone dialing system to any telephone number provided by any Merchant or Guarantor in this Agreement or any application for funding, including cellular phone numbers and landlines, regardless of their inclusion on any do-not-call list, for purposes of servicing, collections, marketing, or promoting any product offered by Buyer.\nEach Merchant and Guarantor are not required to consent to the marketing portion of the foregoing as a condition of qualifying for or obtaining the funding under this Agreement. To opt out of marketing or promotional contact, Merchant or Guarantor may notify Buyer in writing at the address set forth in Section 7.3.\nEach Merchant and Guarantor may revoke the consent given in this Section at any time by any reasonable means, including by replying STOP to a text message, by telephone, or by email to the address in Section 7.3, and Buyer will honour the revocation for all contact that is not required to service this Agreement. Revoking consent does not affect any other right or obligation under this Agreement.\nEach Merchant grants Buyer the right to enter and observe Merchant's premises during business hours, without prior notice, at any time after the occurrence of an Event of Default, for the purpose of protecting Buyer's interest in the Receivables and the Collateral.",
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: ['tcpa-consent-not-revocable-as-promised'] }],
  },
  {
    slug: 'frpa.contractual-statutes-of-limitations-7-19',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    /*
      Same bundle.
    */
    includeWhen: (facts) => facts.disputeResolution === 'courts',
    number: '7.19',
    section: 'miscellaneous',
    sortKey: 190,
    heading: 'Contractual Statutes of Limitations',
    body: 'Each Merchant and Guarantor agrees that any claim, whether sounding in contract, tort, law, equity, or otherwise, that is not asserted against Buyer within one (1) year after its accrual will be time-barred and forever waived, except to the extent such limitation is prohibited by applicable law.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-01',
        findings: [
          'frpa-arbitration-clauses-with-no-arbitration-agreement',
          'one-year-limitations-one-sided',
          'orphan-arbitration-references',
          'orphan-arbitration-twenty-day-bar',
        ],
      },
    ],
  },
  {
    slug: 'frpa.counterclaim-waiver-7-20',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    /*
      Same bundle. Under arbitration the rules of the forum govern instead.
    */
    includeWhen: (facts) => facts.disputeResolution === 'courts',
    number: '7.20',
    section: 'miscellaneous',
    sortKey: 200,
    heading: 'Counterclaim Waiver',
    body: 'In any litigation commenced by Buyer to enforce this Agreement, the Guaranty, or any related agreement, no Merchant or Guarantor will be permitted to interpose any counterclaim, except for any counterclaim arising out of the same transaction or occurrence as Buyer’s claim, which Merchant and Guarantor may assert in that proceeding. Any non-compulsory counterclaim must be brought as a separate proceeding.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-01',
        findings: [
          'counterclaim-waiver-flips-by-forum',
          'frpa-arbitration-clauses-with-no-arbitration-agreement',
          'orphan-arbitration-references',
          'orphan-arbitration-twenty-day-bar',
        ],
      },
    ],
  },
  {
    slug: 'frpa.independent-sales-organizations-and-brokers-7-21',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    includeWhen: null,
    number: '7.21',
    section: 'miscellaneous',
    sortKey: 210,
    heading: 'Independent Sales Organizations and Brokers',
    body: "Each Merchant and Guarantor acknowledges that Merchant may have been introduced to Buyer by, or received assistance in entering into this Agreement from, an independent sales organization, broker, or marketing affiliate (“ISO”). Each Merchant and Guarantor agrees that any ISO is separate from and is not an agent or representative of Buyer, and that Buyer is not bound by any promises, representations, or agreements made by any ISO that are not expressly contained in this Agreement. Each Merchant and Guarantor agrees to indemnify and hold harmless Buyer and its officers, directors, members, shareholders, employees, and agents from and against all losses, damages, claims, liabilities, and expenses (including reasonable attorneys' fees and expert fees) resulting from any act or omission by any ISO. Buyer’s agreements with its ISOs prohibit an ISO from charging, accepting or soliciting any fee or other consideration from a merchant in connection with any financing; the commission Buyer pays is the ISO’s entire compensation. Merchant is therefore not required to pay any ISO anything as a condition of this Agreement, and should notify Buyer at once if any ISO asks it to. If Merchant nevertheless pays an ISO a fee, Buyer will on notice require the ISO to refund it to Merchant.",
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      { review: 'REVIEW-01', findings: ['iso-channel-vs-never-cold-call'] },
      { review: 'REVIEW-02', findings: ['iso-a6-and-frpa-7-21-give-different-answers-about-a-merchant-paid-fee'] },
    ],
  },
  {
    slug: 'frpa.attorney-review-7-22',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    includeWhen: null,
    number: '7.22',
    section: 'miscellaneous',
    sortKey: 220,
    heading: 'Attorney Review',
    body: 'Each Merchant and Guarantor acknowledges that it has had an opportunity to review this Agreement and all addenda with counsel of its choosing before signing or has chosen not to avail itself of that opportunity. Each Merchant and Guarantor further acknowledges that it has not relied on any representation by Buyer or any third party that is not set forth in this Agreement.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-02',
        findings: [
          'frpa-4-8-conditions-the-counsel-review-7-22-promises',
          'frpa-7-10-jury-waiver-recites-what-7-22-contemplates-is-false',
        ],
      },
    ],
  },
  {
    slug: 'frpa.tmf-match-reporting-consent-and-release-7-23',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    includeWhen: null,
    number: '7.23',
    section: 'miscellaneous',
    sortKey: 230,
    heading: 'TMF/MATCH Reporting Consent and Release',
    body: 'Merchant acknowledges and consents that, in connection with this Agreement and any related processor relationship, Buyer or its assignees, servicers, or processor partners may report Merchant or any of its principals to industry-standard databases including but not limited to the Member Alert to Control High-risk Merchants (MATCH) database operated by Mastercard and the Terminated Merchant File (TMF), where such reporting is permitted by applicable card-network rules and applicable law. Merchant waives and releases Buyer and its assignees, servicers, and processor partners from any claim arising from such reporting that is consistent with applicable law and card-network rules.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: ['information-sharing-only-vs-any-third-party'] }],
  },
  {
    slug: 'frpa.state-law-riders-7-24',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    includeWhen: null,
    number: '7.24',
    section: 'miscellaneous',
    sortKey: 240,
    heading: 'State Law Riders',
    body: 'To the extent any provision of this Agreement is prohibited or rendered unenforceable by the law of the state in which Merchant is located, including Conn. Gen. Stat. §36a-868 (which bars a waiver of a recipient’s right to notice, judicial hearing or prior court order in connection with a prejudgment remedy) and Tex. Fin. Code §398.055 (which voids confession-of-judgment and similar provisions), that provision does not apply to this Agreement and the remainder of the Agreement continues in effect. Nothing in Section 7.12 or Section 10 waives any right to notice, to a judicial hearing, or to a prior court order that the law of Merchant’s state makes non-waivable.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-02',
        findings: [
          'frpa-7-24-answers-only-half-of-conn-gen-stat-36a-868',
          'frpa-7-24-does-not-name-the-statute-that-actually-bites',
          'frpa-7-24-misstates-what-tex-fin-code-398-055-voids',
        ],
      },
    ],
  },
  {
    slug: 'frpa.renewal-eligibility-8-1',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    /*
      Renewal eligibility presupposes renewal.
    */
    includeWhen: (facts) => facts.renewalModel !== 'none',
    number: '8.1',
    section: 'renewal',
    sortKey: 10,
    heading: 'Renewal Eligibility',
    body: 'Merchant may be eligible for a renewal funding prior to full collection of the Purchased Amount under this Agreement, subject to Buyer’s underwriting approval. Any renewal shall be documented under a new Future Receivables Purchase Agreement incorporating the outstanding balance from this Agreement.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: ['lombard-multi-position-vs-no-stack'] }],
  },
  {
    slug: 'frpa.rollover-methods-8-2',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    /*
      Carry IS the fact. A payoff-only funder has no rollover method to describe.
    */
    includeWhen: (facts) => facts.renewalModel === 'carry',
    number: '8.2',
    section: 'renewal',
    sortKey: 20,
    heading: 'Rollover Methods',
    body: 'If Merchant has an outstanding Remaining Balance at the time of renewal, the balance shall be handled by whichever of the following methods Merchant elects. Under both methods the Purchase Price is the consideration for the new Purchased Amount, and Merchant may apply part of the Purchase Price to satisfy an existing obligation, whether owed to Buyer or to another funder:\n(a) Deduct. The outstanding Remaining Balance is satisfied out of the Purchase Price, and appears as “Less: Prior Balance(s)” in the itemization in Section 1.4. The new Purchased Amount is Purchase Price × Factor Rate. Merchant receives a reduced disbursement because part of the Purchase Price has been applied to retire the existing obligation, in the same way as if it had been applied to retire an obligation owed to another funder. Where the obligation retired is owed to Buyer, the amount of the new financing used to pay unpaid finance charges on it is disclosed to Merchant on any state disclosure that requires it.\n(b) Carry. The outstanding Remaining Balance is carried into the new Purchased Amount rather than paid off, so that the new Purchased Amount is (Purchase Price × Factor Rate) + Remaining Balance. The Remaining Balance is carried at face value and no Factor Rate is applied to it. “Less: Prior Balance(s)” in Section 1.4 is $0.00 under this method. Merchant receives the full Net Amount Funded, but the total delivery obligation increases by the rollover amount.\nThe Deduct or Carry method applicable to any renewal shall be elected by Merchant. Because the two methods produce different Purchased Amounts, the election is made before this Agreement is issued for signature: Buyer shall explain both methods and the Purchased Amount each produces, Merchant elects, and the elected method is recorded in Section 1 as the Rollover Method with the Purchased Amount in Section 1.3 calculated on that method. Buyer may propose a method when presenting the offer, but Merchant may require the other, in which case Buyer shall re-issue the offer priced on the method Merchant elects. Merchant is not bound by a proposed method it has not elected.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-01',
        findings: [
          'frontload-refactors-old-balance',
          'frpa-undefined-capitalised-terms',
          'lombard-multi-position-vs-no-stack',
          'purchased-amount-two-formulas',
        ],
      },
    ],
  },
  {
    slug: 'frpa.voluntary-prepayment-8-3',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    includeWhen: null,
    number: '8.3',
    section: 'renewal',
    sortKey: 30,
    heading: 'Voluntary Prepayment',
    body: 'Merchant may, at any time and without penalty, deliver to Buyer any or all of the unpaid Purchased Amount before its full collection in the ordinary course. Voluntary prepayment shall not relieve Merchant of any obligation accrued prior to the prepayment date, but shall extinguish all future remittance obligations under this Agreement upon receipt of the full Purchased Amount.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-01',
        findings: ['defined-term-drift', 'frpa-undefined-capitalised-terms', 'undefined-money-terms'],
      },
    ],
  },
];
