import type { McaClause } from '../types';

/**
 * The deal itself — Section 1’s notes, the parties, the grant.
 *
 * Bodies are the words the shipped document prints.
 * `__tests__/frpa-coverage.test.ts` additionally asserts that NOTHING in the
 * document is missing from the library — the direction that fails silently.
 */
export const FRPA_PREAMBLE: McaClause[] = [
  {
    slug: 'frpa.holdback-explainer',
    version: 1,
    instrument: 'frpa',
    number: '',
    section: 'funding-terms',
    sortKey: 10,
    heading: '',
    body: 'What is the Estimated Daily Holdback? The Estimated Daily Holdback is an estimate of the Specified Percentage of Merchant’s average sales revenue. The Estimated Daily Holdback is an informational estimate only; collection occurs exclusively through the Specified Percentage withheld by the Approved Processor from Merchant’s card settlement proceeds. Refer to Section 3 (Reconciliation and Adjustment) for how Merchant may adjust the Estimated Daily Holdback. A separate Split Funding Authorization (Exhibit A) shall be executed for each Approved Processor identified above.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
  },
  {
    slug: 'frpa.equipment-cost-explainer',
    version: 1,
    instrument: 'frpa',
    number: '',
    section: 'funding-terms',
    sortKey: 20,
    heading: '',
    body: 'What is the Equipment Cost? Point-of-sale equipment may be paid for in one of two ways, and only one. Either the cost is added to the Purchased Amount and repaid through the Specified Percentage (“Equipment Cost Deferred” in Section 1.3), or it is deducted from the Purchase Price at funding (“Less: Equipment fee (paid at funding)” in Section 1.4). Under either, Merchant owns the equipment outright. If either figure is greater than $0.00, Merchant is not asked to lease the same equipment and no monthly lease payment is payable for it. If instead Merchant leases the equipment under a separate Equipment Lease Agreement with Lombard Pay LLC, both figures in Section 1 are stated as $0.00 rather than left blank. In no event does Merchant pay for the same equipment under both this Agreement and an Equipment Lease Agreement.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
  },
  {
    slug: 'frpa.equipment-cost-exclusivity',
    version: 1,
    instrument: 'frpa',
    number: '',
    section: 'funding-terms',
    sortKey: 30,
    heading: '',
    body: 'Only one of “Equipment Cost Deferred” in Section 1.3 and “Less: Equipment fee (paid at funding)” in Section 1.4 may be completed with an amount greater than $0.00; the other must be stated as $0.00. The Purchased Amount shown in Section 1.3 is calculated as (Purchase Price × Factor Rate) + Equipment Cost Deferred, and is therefore inclusive of any Equipment Cost Deferred. Because that amount is the price of goods and not a cost of the financing, it is excluded from the finance charge and from the amount financed stated on any state disclosure accompanying this Agreement.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
  },
  {
    slug: 'frpa.rollover-method-election',
    version: 1,
    instrument: 'frpa',
    number: '',
    section: 'funding-terms',
    sortKey: 40,
    heading: '',
    body: 'Rollover Method (renewals only): _________«25»_________. This states the method Merchant elected under Section 8.2 — Deduct or Carry — and the Purchased Amount in Section 1.3 is calculated on it. On a first-time transaction with no prior balance, this reads “Not applicable”.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
  },
  {
    slug: 'frpa.parties',
    version: 1,
    instrument: 'frpa',
    number: '',
    section: 'preamble',
    sortKey: 10,
    heading: '',
    body: 'This Future Receivables Purchase Agreement (this “Agreement”) is entered into and effective as of ____«31»_____ (the “Effective Date”) by and between Lombard Capital LLC, a Florida limited liability company, with its principal office at _______________«96»_______________ (the “Buyer”), and _____________«32»_____________ (the “Merchant” or “Seller”), with reference to the Merchant Information, Deposit Account, Funding Terms, Itemization, and Approved Processors set forth in Section 1 above.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
  },
  {
    slug: 'frpa.granting-clause',
    version: 1,
    instrument: 'frpa',
    number: '',
    section: 'preamble',
    sortKey: 20,
    heading: '',
    body: 'Effective as of the Purchase Date, Merchant hereby sells, assigns and transfers to Buyer (making Buyer the absolute owner) in consideration of the funds provided (the “Purchase Price”), all of Merchant’s future accounts, contract rights and other obligations arising from or relating to the payment of monies from Merchant’s customers and/or other third-party payors (collectively, the “Receipts”), defined as all payments made by cash, check, credit or debit card, electronic transfer or other form of monetary payment in the ordinary course of Merchant’s business, until the amount specified herein (the “Purchased Amount”) has been received by Buyer.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
  },
];
