import type { McaClause } from '../types';

/**
 * Sections 2 and 3 — the sale, its collection and its reconciliation.
 *
 * Bodies are the words the shipped document prints.
 * `__tests__/frpa-coverage.test.ts` additionally asserts that NOTHING in the
 * document is missing from the library — the direction that fails silently.
 */
export const FRPA_PURCHASE: McaClause[] = [
  {
    slug: 'frpa.definitions',
    version: 1,
    instrument: 'frpa',
    number: '',
    section: 'purchase',
    sortKey: 5,
    heading: '',
    body: 'In this Agreement, “Workday” means any day other than a Saturday, a Sunday or a federal banking holiday; “Approved Bank Account” means the deposit account identified in Section 1 into which Merchant deposits Receipts; and “Approved Processor” means the credit and debit card processor identified in Section 1 or otherwise approved by Buyer in writing.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
  },
  {
    slug: 'frpa.sales-of-receipts-not-a-loan-2-1',
    version: 1,
    instrument: 'frpa',
    number: '2.1',
    section: 'purchase',
    sortKey: 10,
    heading: 'Sales of Receipts; Not a Loan',
    body: 'Merchant and Buyer agree that the Purchase Price is in exchange for the Purchased Amount and shall not be construed as a loan from Buyer to Merchant. There is no time certain when the Purchased Amount will be received by Buyer since collection is based solely upon Buyer’s receipt of the Specified Percentage. Merchant agrees that the Purchase Price equals the fair market value of the Receipts and that Buyer has purchased and shall own all the Receipts described herein up to the full Purchased Amount as the Receipts are created. If any amount payable to Buyer under this Agreement is determined to exceed the maximum amount permitted by applicable law, that amount shall automatically be reduced to the maximum amount permitted, and Buyer shall promptly refund any excess to Merchant.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-01',
        findings: [
          'fair-market-value-recital-self-refuting',
          'indemnity-charges-interest-document-denies',
          'interest-charges-inside-a-not-a-loan',
          'usury-defence-waiver-void',
        ],
      },
    ],
  },
  {
    slug: 'frpa.collection-mechanism-and-term-2-2',
    version: 1,
    instrument: 'frpa',
    number: '2.2',
    section: 'purchase',
    sortKey: 20,
    heading: 'Collection Mechanism and Term',
    body: "The Purchased Amount shall be delivered to Buyer through the Approved Processor as set forth in Section 2.3 (Primary Collection: Split Funding via Approved Processor), via withholding of the Specified Percentage of Merchant's daily credit and debit card receipts. The Estimated Daily Holdback set forth in Section 1 is informational and represents Buyer's estimate of average daily collection assuming Merchant's projected sales; actual daily collection varies with Merchant's actual sales volume and may be greater or less than the Estimated Daily Holdback on any given Workday. This Agreement shall continue until the Completion Threshold defined in Section 2.6 is attained.",
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-01',
        findings: [
          'acceleration-defeats-indefinite-term',
          'default-collection-reaches-cash-and-checks',
          'defined-term-drift',
          'frpa-22-cites-wrong-clause-title',
        ],
      },
    ],
  },
  {
    slug: 'frpa.primary-collection-split-funding-via-approved-processor-2-3',
    version: 1,
    instrument: 'frpa',
    number: '2.3',
    section: 'purchase',
    sortKey: 30,
    heading: 'Primary Collection: Split Funding via Approved Processor',
    body: 'Merchant hereby authorizes Buyer to receive payment of the Specified Percentage of Merchant’s daily credit and debit card receivables directly from Merchant’s credit card processor and/or acquiring bank. Merchant agrees to execute any documentation required by the processor to enable this arrangement, including but not limited to a split-funding letter or processor instruction form.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
  },
  {
    slug: 'frpa.approved-bank-account-2-4',
    version: 1,
    instrument: 'frpa',
    number: '2.4',
    section: 'purchase',
    sortKey: 40,
    heading: 'Approved Bank Account',
    body: 'During the term of this Agreement, Merchant shall: (i) deposit all Receipts into one and only one bank account, which bank account shall be acceptable and preapproved by Buyer (the “Approved Bank Account”); (ii) use one and only one credit card processor, which processor shall be acceptable and preapproved by Buyer (the “Approved Processor”); and (iii) deposit all credit card receipts into the Approved Bank Account. In the event the Approved Bank Account or Approved Processor becomes unavailable or ceases providing services to Merchant during the term of this Agreement, prior to the first date of such unavailability, Merchant shall arrange for another Approved Bank Account or Approved Processor.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
  },
  {
    slug: 'frpa.reserved-2-5',
    version: 1,
    instrument: 'frpa',
    number: '2.5',
    section: 'purchase',
    sortKey: 50,
    heading: '[Reserved]',
    body: '[Reserved]',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
  },
  {
    slug: 'frpa.completion-threshold-2-6',
    version: 1,
    instrument: 'frpa',
    number: '2.6',
    section: 'purchase',
    sortKey: 60,
    heading: 'Completion Threshold',
    body: '“Remaining Balance” means, at any time, the Purchased Amount plus any fees charged under Section 4.1 and Appendix A, less all amounts collected by Buyer. This Agreement is complete and Buyer’s right to receive Receipts terminates when the Remaining Balance is zero or less (the “Completion Threshold”). That is the only test; where any other provision of this Agreement describes completion differently, this Section governs. Upon attainment of the Completion Threshold, all Specified Percentage withholdings under this Agreement shall automatically cease.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-01',
        findings: [
          'completion-threshold-two-conflicting-tests',
          'frpa-undefined-capitalised-terms',
          'undefined-money-terms',
        ],
      },
      {
        review: 'REVIEW-02',
        findings: [
          'frpa-7-6-and-4-2-contradict-the-2-6-completion-test',
          'payzli-cessation-on-notice-vs-frpa-2-6-automatic-cessation',
          'payzli-instruction-stops-short-of-the-frpa-completion-threshold',
        ],
      },
    ],
  },
  {
    slug: 'frpa.merchant-s-right-to-reconciliation-3-1',
    version: 1,
    instrument: 'frpa',
    number: '3.1',
    section: 'reconciliation',
    sortKey: 10,
    heading: 'Merchant’s Right to Reconciliation',
    body: 'If at any time during the term of this Agreement Merchant experiences an unforeseen decrease or increase in its Daily Receipts, Merchant shall have the right, at its sole and absolute discretion but subject to the procedure set forth below, to request retroactive reconciliation of the Estimated Daily Holdback for one (1) full calendar month immediately preceding the day when such request for reconciliation is received by Buyer (each such calendar month, a “Reconciliation Month”).\nSuch reconciliation (the “Reconciliation”) shall be performed by Buyer within five (5) Workdays following its receipt of the Merchant’s request by crediting any over-collected difference back to Merchant, or correcting any under-collection prospectively through the Approved Processor split, so that the total amount collected by Buyer during the Reconciliation Month is equal to the Specified Percentage of the Receipts that Merchant collected during that month. One or more Reconciliation procedures may reduce or increase the effective Estimated Daily Holdback and may shorten or extend the term of this Agreement.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: ['defined-term-drift', 'undefined-money-terms'] }],
  },
  {
    slug: 'frpa.request-for-reconciliation-procedure-3-2',
    version: 1,
    instrument: 'frpa',
    number: '3.2',
    section: 'reconciliation',
    sortKey: 20,
    heading: 'Request for Reconciliation Procedure',
    body: 'It shall be Merchant’s sole responsibility to initiate Reconciliation by sending a written request to Buyer. Each request shall include a copy of Merchant’s bank statement and credit card processing statements for the Reconciliation Month at issue (the “Reconciliation Information”) and shall be received by Buyer within thirty (30) Workdays after the last day of the Reconciliation Month at issue. A request received after that period is not nullified; Buyer shall perform the Reconciliation for the month at issue if the Reconciliation Information supports it. Notwithstanding Section 7.3, a request for Reconciliation or an Adjustment may be sent by email to the address stated in Section 1, and is effective on receipt.\nMerchant shall have the right to request Reconciliation as many times during the term of this Agreement as it deems proper, provided that each request is made in accordance with this section. If a request is made after the expiration of the term of this Agreement and the total amount actually collected by Buyer is less than the Purchased Amount, the term of this Agreement shall automatically be extended until the total amount collected equals the Purchased Amount.\nNothing in this section shall modify the Estimated Daily Holdback for any calendar month other than the Reconciliation Month(s) as the result of the Reconciliation.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-01',
        findings: [
          'acceleration-defeats-indefinite-term',
          'reconciliation-right-conditioned-into-near-nullity',
          'reconciliation-switched-off-by-any-breach',
        ],
      },
    ],
  },
  {
    slug: 'frpa.failure-to-provide-reconciliation-information-3-3',
    version: 1,
    instrument: 'frpa',
    number: '3.3',
    section: 'reconciliation',
    sortKey: 30,
    heading: 'Failure to Provide Reconciliation Information',
    body: 'If Merchant requests a Reconciliation and fails to provide the Reconciliation Information within five (5) Workdays after the request, Buyer may consider the request withdrawn. If Buyer requests a reconciliation and Merchant fails to provide the Reconciliation Information within five (5) Workdays, Buyer may adjust the Estimated Daily Holdback based on the best information reasonably available. Any request for reconciliation must be initiated prior to the payoff of the Purchased Amount plus any other sums due. Merchant’s refusal to deliver Reconciliation Information pursuant to Buyer’s request may be considered interference with Buyer’s rights and deemed a default of this Agreement.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-01',
        findings: [
          'frpa-undefined-capitalised-terms',
          'periodic-amount-undefined-fixed-draw-residue',
          'reconciliation-right-conditioned-into-near-nullity',
          'reconciliation-switched-off-by-any-breach',
          'undefined-money-terms',
        ],
      },
    ],
  },
  {
    slug: 'frpa.adjustment-of-the-estimated-daily-holdback-3-4',
    version: 1,
    instrument: 'frpa',
    number: '3.4',
    section: 'reconciliation',
    sortKey: 40,
    heading: 'Adjustment of the Estimated Daily Holdback',
    body: 'If at any time during the term of this Agreement Merchant experiences a steady decrease in its Receipts, Merchant shall have the right, at its sole and absolute discretion, to request a modification (the “Adjustment”) of the Estimated Daily Holdback. Where the request is supported by the Reconciliation Information, Buyer shall grant the Adjustment; Buyer has no discretion to withhold it. The Adjustment shall become effective as of the date the request is received by Buyer, and the new Adjusted Daily Holdback shall replace and supersede the Estimated Daily Holdback set forth above. The Adjustment shall be performed by Buyer within five (5) Workdays following its receipt of the request. Merchant’s right to request Reconciliation under Section 3.1 and an Adjustment under this Section survives an Event of Default and may be exercised while an Event of Default is continuing. One or more Adjustments may substantially extend the term of this Agreement.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-01',
        findings: [
          'defined-term-drift',
          'frpa-undefined-capitalised-terms',
          'periodic-amount-undefined-fixed-draw-residue',
          'undefined-money-terms',
        ],
      },
    ],
  },
];
