import type { McaClause } from '../types';

/**
 * Section 5 — representations, warranties and covenants.
 *
 * Bodies are the words the shipped document prints.
 * `__tests__/frpa-coverage.test.ts` additionally asserts that NOTHING in the
 * document is missing from the library — the direction that fails silently.
 */
export const FRPA_REPRESENTATIONS: McaClause[] = [
  {
    slug: 'frpa.representations-lead-in',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    number: '',
    section: 'representations',
    sortKey: 5,
    heading: '',
    body: 'Merchant represents, warrants, and covenants that as of the Effective Date and during the term of this Agreement:',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
  },
  {
    slug: 'frpa.advances-are-not-loans-5-1',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    number: '5.1',
    section: 'representations',
    sortKey: 10,
    heading: 'Advances are not Loans',
    body: 'Merchant fully understands that the Purchase Price is not a loan, but a non-recourse transaction pursuant to which Buyer’s funds are at full risk of non-payment in the event Receipts are not sufficient to satisfy the Purchased Amount, and that it is not possible to determine the time period within which the Specified Percentage of Receipts will last to satisfy the Purchased Amount.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-01',
        findings: [
          'all-assets-lien-vs-nonrecourse-recital',
          'business-interruption-insurance-defeats-risk',
          'usury-defence-waiver-void',
          'usury-defense-waiver',
        ],
      },
    ],
  },
  {
    slug: 'frpa.financial-condition-and-financial-information-5-2',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    number: '5.2',
    section: 'representations',
    sortKey: 20,
    heading: 'Financial Condition and Financial Information',
    body: 'Merchant’s bank and financial statements, copies of which have been furnished to Buyer, and any future statements that may be furnished, fairly represent the financial condition of Merchant at the dates indicated, and since those dates there has been no material adverse change, financial or otherwise, in Merchant’s condition, operation, or ownership. Merchant has a continuing affirmative obligation to advise Buyer of any material adverse change in its financial condition, operation, or ownership. Buyer may request statements at any time during the performance of this Agreement, and Merchant shall provide them within five (5) business days after the request. Merchant’s failure to provide them is a material breach of this Agreement.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: ['guaranty-covers-every-covenant', 'no-cure-period-anywhere'] }],
  },
  {
    slug: 'frpa.governmental-approvals-5-3',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    number: '5.3',
    section: 'representations',
    sortKey: 30,
    heading: 'Governmental Approvals',
    body: 'Merchant is in compliance with, and shall comply with, all applicable federal, state, and local laws and regulations, and has all valid permits, authorizations, and licenses necessary to own, operate, and lease its properties and to conduct the business in which it is presently engaged. Merchant has filed all federal, state, and local tax returns required to be filed and has paid all taxes shown thereon to be due and payable, except for taxes being contested in good faith and for which adequate reserves have been provided. Merchant has no outstanding tax liens against any of its assets or Receipts.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      { review: 'REVIEW-02', findings: ['frpa-5-3-and-5-14-give-the-same-compliance-representation-twice'] },
    ],
  },
  {
    slug: 'frpa.authorization-5-4',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    number: '5.4',
    section: 'representations',
    sortKey: 40,
    heading: 'Authorization',
    body: 'Merchant, and the person(s) signing this Agreement on behalf of Merchant, have full power and authority to incur and perform the obligations under this Agreement, all of which have been duly authorized.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: ['debt-vocabulary-the-language-guard-would-not-catch'] }],
  },
  {
    slug: 'frpa.insurance-5-5',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    number: '5.5',
    section: 'representations',
    sortKey: 50,
    heading: 'Insurance',
    body: 'To the extent Merchant maintains property or casualty insurance covering the Collateral, Merchant will name Buyer as loss payee as to the Collateral and will provide proof of that coverage on request. Merchant is not required to carry business-interruption insurance for Buyer’s benefit, and Buyer takes no interest in any policy that would pay Buyer because Merchant’s Receipts have fallen.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-01',
        findings: [
          'business-interruption-insurance-defeats-risk',
          'guaranty-covers-every-covenant',
          'no-cure-period-anywhere',
        ],
      },
    ],
  },
  {
    slug: 'frpa.the-account-5-6',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    number: '5.6',
    section: 'representations',
    sortKey: 60,
    heading: 'The Account',
    body: 'Merchant will not change the Approved Bank Account or take any other action that could have any adverse effect upon Merchant’s obligations under this Agreement, without Buyer’s prior written consent. Any such change shall be a material breach of this Agreement.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-01',
        findings: ['defined-term-drift', 'frpa-undefined-capitalised-terms', 'no-cure-period-anywhere'],
      },
    ],
  },
  {
    slug: 'frpa.reserved-5-7',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    number: '5.7',
    section: 'representations',
    sortKey: 70,
    heading: '[Reserved]',
    body: '[Reserved]',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: ['frpa-5-7-duplicates-5-18'] }],
  },
  {
    slug: 'frpa.estoppel-certificate-5-8',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    number: '5.8',
    section: 'representations',
    sortKey: 80,
    heading: 'Estoppel Certificate',
    body: 'Merchant will at any time, upon at least one (1) day’s prior notice from Buyer, execute, acknowledge, and deliver to Buyer or to any other person specified by Buyer a statement certifying that this Agreement is unmodified and in full force and effect (or, if there have been modifications, stating the modifications) and stating the dates which the Purchased Amount or any portion thereof has been delivered.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: ['no-cure-period-anywhere'] }],
  },
  {
    slug: 'frpa.no-bankruptcy-5-9',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    number: '5.9',
    section: 'representations',
    sortKey: 90,
    heading: 'No Bankruptcy',
    body: 'As of the date of this Agreement, Merchant does not contemplate and has not filed any petition for bankruptcy protection under Title 11 of the United States Code, and there has been no involuntary petition brought or pending against Merchant.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      { review: 'REVIEW-01', findings: ['bankruptcy-carveout-defeated-by-5-9', 'guaranty-reaches-business-failure'] },
    ],
  },
  {
    slug: 'frpa.no-encumbrance-of-receipts-5-10',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    number: '5.10',
    section: 'representations',
    sortKey: 100,
    heading: 'No Encumbrance of Receipts',
    body: 'Merchant shall not further encumber the Receipts without the prior written consent of Buyer, other than the monthly Equipment payment billed at merchant level by the Approved Processor under an Equipment Lease Agreement between Merchant and {{equipmentAffiliate}}, which is a permitted claim ranking after the Specified Percentage.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
  },
  {
    slug: 'frpa.unencumbered-receipts-5-11',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    number: '5.11',
    section: 'representations',
    sortKey: 110,
    heading: 'Unencumbered Receipts',
    body: 'Merchant has good, complete, and marketable title to all Receipts, free and clear of any and all liabilities, liens, claims, charges, restrictions, conditions, options, rights, mortgages, security interests, equities, pledges, and encumbrances of any kind or nature whatsoever, or any other rights or interests that may be inconsistent with the transactions contemplated with, or adverse to the interests of, Buyer, other than the monthly Equipment payment billed at merchant level by the Approved Processor under an Equipment Lease Agreement between Merchant and {{equipmentAffiliate}}, which is a permitted claim ranking after the Specified Percentage.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      { review: 'REVIEW-02', findings: ['frpa-5-11-and-5-13-route-personal-liability-through-the-narrowed-9-2'] },
    ],
  },
  {
    slug: 'frpa.business-purpose-5-12',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    number: '5.12',
    section: 'representations',
    sortKey: 120,
    heading: 'Business Purpose',
    body: 'Merchant is a valid business in good standing under the laws of the jurisdictions in which it is organized and operates, and Merchant is entering into this Agreement for business purposes and not as a consumer for personal, family, or household purposes. Merchant’s principal place of business is the Business Address stated in Section 1.1.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      { review: 'REVIEW-02', findings: ['frpa-5-12-does-not-state-the-merchants-principal-place-of-business'] },
    ],
  },
  {
    slug: 'frpa.defaults-under-other-contracts-improper-transfers-5-13',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    number: '5.13',
    section: 'representations',
    sortKey: 130,
    heading: 'Defaults under Other Contracts; Improper Transfers',
    body: 'Merchant’s execution of and performance under this Agreement will not cause or create an event of default by Merchant under any contract with another person or entity, nor will it be considered a fraudulent transfer or fraudulent conveyance, or otherwise be void or voidable under similar laws or principles, the doctrine of equitable subordination, laws regarding preferential transfers, or for any other reason.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      { review: 'REVIEW-02', findings: ['frpa-5-11-and-5-13-route-personal-liability-through-the-narrowed-9-2'] },
    ],
  },
  {
    slug: 'frpa.civil-criminal-regulatory-matters-5-14',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    number: '5.14',
    section: 'representations',
    sortKey: 140,
    heading: 'Civil/Criminal/Regulatory Matters',
    body: 'There are no civil or criminal proceedings pending before any court, government agency, arbitration panel, or administrative tribunal, or, to Merchant’s knowledge, threatened against Merchant, that may result in any material adverse change in the business, property, or financial condition of Merchant.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      { review: 'REVIEW-02', findings: ['frpa-5-3-and-5-14-give-the-same-compliance-representation-twice'] },
    ],
  },
  {
    slug: 'frpa.business-closure-5-15',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    number: '5.15',
    section: 'representations',
    sortKey: 150,
    heading: 'Business Closure',
    body: 'At no time during the six (6) months immediately preceding the date of this Agreement has Merchant decided to close or cease operating its business, in whole or in part, temporarily or permanently.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: ['guaranty-reaches-business-failure'] }],
  },
  {
    slug: 'frpa.stacking-prohibited-5-16',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    number: '5.16',
    section: 'representations',
    sortKey: 160,
    heading: 'Stacking Prohibited',
    body: 'Merchant shall not, without Buyer’s prior written consent, sign any agreement for the sale of future receipts with any party other than Buyer for the duration of this Agreement. Buyer may share information regarding this Agreement with any third party in order to determine whether Merchant is in compliance with this provision.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: ['information-sharing-only-vs-any-third-party'] }],
  },
  {
    slug: 'frpa.no-diversion-of-receipts-5-17',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    number: '5.17',
    section: 'representations',
    sortKey: 170,
    heading: 'No Diversion of Receipts',
    body: 'Merchant must deposit all Receipts into the Approved Bank Account on a daily basis and must instruct Merchant’s credit card processor (which must be approved by Buyer) to deposit all credit and debit card Receipts of Merchant into the Approved Bank Account on a daily basis, net only of the Specified Percentage remitted to Buyer under Section 2.3 and of the monthly Equipment payment billed at merchant level by the Approved Processor under an Equipment Lease Agreement between Merchant and {{equipmentAffiliate}}, which is a permitted claim ranking after the Specified Percentage. Merchant agrees not to: (i) change the Approved Bank Account without the express written consent of Buyer; (ii) add an additional Account; (iii) close the Approved Bank Account without the express written consent of Buyer; or (iv) take any other action with the intent to interfere with Buyer’s right to collect the purchased Receipts.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      { review: 'REVIEW-01', findings: ['defined-term-drift'] },
      { review: 'REVIEW-02', findings: ['frpa-undefined-capitalised-terms-in-the-unexamined-clauses'] },
    ],
  },
  {
    slug: 'frpa.change-of-name-or-location-or-sale-or-closing-of-business-5-18',
    version: 1,
    instrument: 'frpa',
    kind: 'clause',
    number: '5.18',
    section: 'representations',
    sortKey: 180,
    heading: 'Change of Name or Location or Sale or Closing of Business',
    body: 'Merchant will not conduct Merchant’s businesses under any name other than as disclosed to Buyer, or change any of its places of business, without prior written consent of Buyer. Merchant will not voluntarily sell, dispose, transfer, or otherwise convey all or substantially all of its business or assets without (i) the express prior written consent of Buyer, and (ii) the written agreement of any purchaser or transferee assuming all of Merchant’s obligations under this Agreement pursuant to documentation satisfactory to Buyer. Except as disclosed to Buyer in writing, Merchant has no current plans to close its business either temporarily or permanently. Merchant will not voluntarily close its business on a temporary basis for renovations, repairs, or any other voluntary purposes. This provision does not prohibit Merchant from closing its business temporarily if such closing is required to conduct renovations or repairs that are required by local ordinance or other legal order, or if otherwise forced to do so by circumstances outside of the control of Merchant. Prior to any such closure, Merchant will provide Buyer ten (10) calendar days’ notice to the extent practicable.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      { review: 'REVIEW-01', findings: ['guaranty-covers-every-covenant'] },
      {
        review: 'REVIEW-02',
        findings: ['frpa-5-7-duplicates-5-18', 'frpa-6-1-4-defaults-on-a-sale-5-18-expressly-permits'],
      },
    ],
  },
];
