import type { McaClause } from '../types';

/**
 * Current draft equipment terms include the coordinated MCA-R08–R12 correction.
 * Source documents and historical review annotations remain provenance; changed
 * versions require fresh approval before publication. See the equipment handoff.
 */
export const SUBSCRIPTION_AGREEMENT: McaClause[] = [
  {
    slug: 'subscription.parties',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'load-bearing',
      note: 'The equipment agreement needs its own provider, customer and effective date; the receivables funder’s profile does not identify these contracting parties.',
    },
    version: 3,
    instrument: 'subscription',
    kind: 'clause',

    includeWhen: null,
    section: 'agreement',
    sortKey: 1,
    heading: 'Parties',
    body: 'The completed grid identifies this Agreement, the parties, the Equipment, the payment schedule and the effective date. We are the equipment counterparty; naming a receivables funder, processor or service provider does not make it a party or establish an affiliation. This Agreement becomes effective only as Section [[clause:subscription.effective-date-term-and-interim-rent]] provides.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: [] }],
  },
  {
    slug: 'subscription.total-payments-estimate',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'no-alternative',
      note: 'This is the equipment contract’s estimate from its monthly charge and term, not a prescribed commercial-financing disclosure; no alternate estimate text is authored.',
    },
    version: 2,
    instrument: 'subscription',
    kind: 'clause',
    includeWhen: null,
    section: 'agreement',
    sortKey: 2,
    heading: 'Estimated Total Payments',
    body: 'The scheduled total in the Subscriber and Equipment Information grid itemizes the monthly charges for the stated term, interim charge, delivery charge, installation charge, purchase price if applicable, and estimated taxes, with every amount counted once. It identifies amounts due at signing, each scheduled due date and the final payment date. Any tax estimate states its basis and is reconciled to the actual applicable tax; contingent repair or enforcement expenses are separately described and are not included as if certain to occur. We provide the completed schedule before you sign and a corrected schedule before an agreed change takes effect. This schedule is not a prescribed commercial-financing disclosure and does not replace a separate disclosure required by the transaction’s actual product classification and applicable law.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: [] }],
  },
  {
    slug: 'subscription.charges-billed',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'load-bearing',
      note: 'This billing pointer must lead to the equipment agreement’s own charge schedule; it does not select the receivables purchase’s collection method.',
    },
    version: 1,
    instrument: 'subscription',
    kind: 'clause',
    includeWhen: null,
    section: 'agreement',
    sortKey: 3,
    heading: 'Billing',
    body: 'Subscription charges and applicable taxes are billed as set out in this Agreement.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: [] }],
  },
  {
    slug: 'subscription.read-before-signing',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'no-alternative',
      note: 'The read-and-complete acknowledgment is the only authored equipment execution legend; no law is identified as requiring this exact warning.',
    },
    version: 1,
    instrument: 'subscription',
    kind: 'clause',
    includeWhen: null,
    section: 'agreement',
    sortKey: 4,
    heading: 'Acknowledgment Before Signing',
    body: 'DO NOT SIGN UNTIL YOU HAVE READ, UNDERSTOOD, AND AGREED TO THE TERMS AND CONDITIONS ON ALL PAGES OF THIS AGREEMENT. NO ATTEMPT AT ORAL MODIFICATION OR RESCISSION OF THIS AGREEMENT OR ANY TERM THEREOF WILL BE BINDING UPON THE PARTIES. SEE SECTION [[clause:subscription.entire-agreement]] OF THE TERMS AND CONDITIONS. BY SIGNING THIS AGREEMENT, THE UNDERSIGNED SUBSCRIBER ACKNOWLEDGES READING ALL PAGES OF THIS AGREEMENT, THAT ALL BLANK TERMS IN THE SUBSCRIBER AND EQUIPMENT INFORMATION GRID WERE FILLED IN AT THE TIME OF SIGNING, AND THAT SUBSCRIBER AGREES TO BE BOUND BY ALL THE TERMS OF THIS AGREEMENT.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: [] }],
  },
  {
    slug: 'subscription.equipment',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'load-bearing',
      note: 'The agreement must identify what equipment the provider supplies and the terms of that supply; no funder fact supplies another equipment description.',
    },
    version: 2,
    instrument: 'subscription',
    kind: 'clause',
    includeWhen: null,
    section: 'agreement',
    sortKey: 10,
    heading: 'Equipment',
    body: 'We will provide the Equipment identified by manufacturer, model, quantity, serial number when available, and installation site in the Subscriber and Equipment Information grid. Any substitution requires your written agreement to its identity, functionality and price before acceptance; we may not substitute equipment unilaterally. We will identify the processing systems with which the Equipment and included software are represented to operate, and deliver the stated installation, support and supplier warranty information before you sign. A change of processor may affect compatibility, but does not excuse a failure to meet our express promises or any right that applicable law preserves.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      { review: 'REVIEW-01', findings: [] },
      { review: 'REVIEW-02', findings: ['el-3-9-sole-and-exclusive-remedies-points-at-an-empty-set'] },
    ],
  },
  {
    slug: 'subscription.effective-date-term-and-interim-rent',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'no-alternative',
      note: 'The equipment commencement, fixed term and capped interim charge are the only authored duration terms; the receivables collection preference does not alter them.',
    },
    version: 2,
    instrument: 'subscription',
    kind: 'clause',
    includeWhen: null,
    section: 'agreement',
    sortKey: 20,
    heading: 'Effective Date, Term, and Interim Rent',
    body: '(a) This Agreement becomes effective when both parties sign it and we deliver a complete copy to you. Delivery alone does not establish assent. The actual Delivery Date is recorded in the Subscriber and Equipment Information grid; we deliver to the agreed site. (b) The Commencement Date and the number of months in the Subscription Term are stated in that grid before signing. The Commencement Date may not precede delivery of the agreed usable Equipment. A delivery delay requires a corrected schedule accepted by both parties; it does not permit us to charge for an undelivered period or unilaterally choose a later commencement. The stated term is a fixed commitment, subject to this Agreement’s express completion, termination and remedy provisions and rights preserved by law. (c) Any interim charge runs only from the actual Delivery Date through the day preceding the agreed Commencement Date, at one-thirtieth of the monthly charge per day, capped at one monthly charge. There is no charge for overlap with a scheduled monthly period. If the stated commencement would fall more than thirty days after delivery, billing cannot start until the parties correct the schedule so that the interim period is no more than thirty days. The actual interim dates and charge must be itemized; amounts paid are credited once. (d) Processing compatibility and any dependence on a separate processing service must be identified before signing under Section [[clause:subscription.equipment]]. Termination of that service does not itself enlarge this Agreement’s charges or the Guaranty.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-01',
        findings: [
          'sub-interim-rent-unbounded',
          'sub-3-7-notice-anchor-and-minimum-term',
          'sub-payment-guaranty-defeats-commitment-3',
        ],
      },
    ],
  },
  {
    slug: 'subscription.site-preparation',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'no-alternative',
      note: 'The customer’s installation preparations are the only authored site duties; no funder fact selects a different installation allocation.',
    },
    version: 1,
    instrument: 'subscription',
    kind: 'clause',
    includeWhen: null,
    section: 'agreement',
    sortKey: 30,
    heading: 'Site Preparation',
    body: 'You will prepare the installation site(s) for the Equipment, including without limitation the power supply circuits and phone lines, in conformance with the manufacturer’s and our specifications, and will make the site(s) available to us by the confirmed shipping date.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: [] }],
  },
  {
    slug: 'subscription.payment-of-amounts-due',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'misattributed',
      note: 'These are the equipment provider’s fixed charges and collection arrangements; the receivables funder’s collection method does not decide a separate provider’s billing terms.',
    },
    version: 2,
    instrument: 'subscription',
    kind: 'clause',
    includeWhen: null,
    section: 'agreement',
    sortKey: 40,
    heading: 'Payment of Amounts Due',
    body: '(a) The completed payment schedule lists every scheduled charge and its due date, including any interim, delivery, installation and purchase charge. We may not add an unlisted periodic or transaction fee. No late fee, default interest, flat collection fee, upgrade fee or assumption fee is imposed by this Agreement. A separately requested change must be priced and signed before it takes effect. Actual permitted repair and enforcement expenses remain subject to Sections [[clause:subscription.use-return-of-equipment-and-insurance]], [[clause:subscription.indemnification]] and [[clause:subscription.default-remedies]], including their caps and credits. (b) We send an itemized invoice to the agreed notice email at least ten days before a scheduled due date; a late invoice extends its due date by the missing notice days without a surcharge. Each regular monthly charge is due on the calendar day stated in the schedule, or the last day of a shorter month. You pay by a separately agreed method. No automatic bank or processor debit is authorized by this Agreement. Any separate debit authorization states the amount or method of determining it, timing and withdrawal procedure; withdrawing it stops future automatic debits and requires an alternative payment method, without changing the amount actually owed. Equipment billing does not increase a receivables purchase’s Specified Percentage or Purchased Amount, divert the purchased share of receipts, or authorize a default sweep. A receivables purchase’s completion does not authorize collecting equipment amounts through that purchase. (c) Taxes are limited to those legally payable by you on this transaction or Equipment, excluding our income taxes. We itemize the jurisdiction, taxable base, rate, actual liability and prior collections; an estimate is reconciled and any overpayment credited or refunded. No unsupported average property-tax charge applies. (d) All payments are credited to the identified invoice once. A cash purchase or equipment deduction recorded under another agreement must not also be billed here. Billing stops as Section [[clause:subscription.return-or-continuation-of-equipment-at-end-of-subscription-term]] provides, while only accrued, unpaid lawful obligations remain. Rights for nonconforming equipment or breach by us are preserved.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-01',
        findings: [
          'sub-fee-schedule-incomplete',
          'sub-late-fee-schedule-vs-operative',
          'sub-no-collection-channel-unbounded-setoff',
          'sub-ungrounded-upgrade-assumption-fees',
          'sub-payment-guaranty-defeats-commitment-3',
        ],
      },
      { review: 'REVIEW-02', findings: ['el-3-4a-declares-itself-exhaustive-and-is-not'] },
    ],
  },
  {
    slug: 'subscription.use-return-of-equipment-and-insurance',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'misattributed',
      note: 'Use, return and insurance concern the provider’s equipment; whether the funder offers equipment does not choose among alternative obligations within this separate agreement.',
    },
    version: 2,
    instrument: 'subscription',
    kind: 'clause',
    includeWhen: null,
    section: 'agreement',
    sortKey: 50,
    heading: 'Use, Return of Equipment, and Insurance',
    body: '(a) Operate the Equipment with qualified personnel according to supplied instructions and maintain it in good condition, ordinary wear excepted. Do not make a material physical alteration, move it from the stated site, sublet it or create a conflicting consensual lien without our reasonable prior written consent while we retain ownership or any legally effective security interest. Comply with applicable operating laws and permits. (b) Inspection or repair requires reasonable notice, an agreed appointment during normal business hours and your consent to entry. This is not consent to forcible entry or self-help contrary to Section [[clause:subscription.default-remedies]]. Labels may accurately identify our ownership and any legally effective security interest; a label does not determine fixture status or lien priority. (c) Where return is required, use the identified return address and a tracked method, reference the agreement number, and retain a receipt. We provide reasonable packing instructions and acknowledge receipt. You owe only documented, reasonable repair costs for damage beyond ordinary wear for which you are responsible, after itemized evidence and an opportunity to dispute the charge. No automatic missing-reference or return-processing penalty applies. Required default accounting and value credits govern every recovery. (d) The grid identifies the required insurance, coverage amount and loss payee, limited to our ownership and any legally effective security interest. We may not require insurance or claim proceeds exceeding our actual insurable interest. A casualty must be reported promptly; insurance and other recovery are credited once. Risk of loss and any resulting payment obligation remain subject to the applicable law, our performance obligations and the remedies and accounting limits of this Agreement.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      { review: 'REVIEW-01', findings: ['frpa-sub-equipment-lien-conflict', 'sub-purchase-residue'] },
      { review: 'REVIEW-02', findings: ['el-3-4a-declares-itself-exhaustive-and-is-not'] },
    ],
  },
  {
    slug: 'subscription.title-to-equipment',
    whyThisClause: {
      kind: 'implements',
      citation:
        'UCC §§9-203, 9-509, as enacted in the governing jurisdiction (e.g. Fla. Stat. §§679.2031(2)(c), 679.509)',
    },
    variance: {
      kind: 'fixed',
      because: 'misattributed',
      note: 'Equipment title and any security interest follow this separate equipment transaction; the funder’s equipment offering and receivables collateral do not decide who owns this equipment.',
    },
    version: 2,
    instrument: 'subscription',
    kind: 'clause',
    includeWhen: null,
    section: 'agreement',
    sortKey: 60,
    heading: 'Title to Equipment',
    body: 'We retain title to the described Equipment; this Agreement provides no purchase option or automatic ownership transfer. Its legal classification depends on the actual transaction, including the fixed term, useful life and residual interest, rather than the word subscription. If applicable law treats the transaction as secured financing, you grant us a security interest only in your rights in the described Equipment and its identifiable proceeds, securing only obligations actually owed under this Agreement. Attachment requires the applicable legal prerequisites, including value, your rights in the collateral and an authenticated security agreement. You authorize a financing statement limited to that collateral to the extent the filing law permits; you do not appoint us to sign another agreement or an amendment for you. Perfection requires the applicable filing or other legal steps, and priority is not guaranteed by this Agreement or a filing. On satisfaction we timely release any security interest and provide required termination records. The actual classification and any applicable commercial-financing disclosure must be evaluated before use; no statutory exemption is created by this paragraph.\nEquipment Charged Only Once. This Agreement is not executed for Equipment already paid for through a cash purchase or equipment cost deducted or deferred under another agreement. You will never pay for the same equipment twice.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-01',
        findings: [
          'equipment-charged-in-both-documents',
          'frpa-sub-equipment-lien-conflict',
          'sub-no-lease-financing-disclosure',
        ],
      },
    ],
  },
  {
    slug: 'subscription.return-or-continuation-of-equipment-at-end-of-subscription-term',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'misattributed',
      note: 'The subscriber chooses return or continuation under this equipment contract, which offers no purchase option; the funder’s equipment-offering answer is not that election.',
    },
    version: 2,
    instrument: 'subscription',
    kind: 'clause',
    includeWhen: null,
    section: 'agreement',
    sortKey: 70,
    heading: 'Return or Continuation of Equipment at End of Subscription Term',
    body: 'This Agreement has no purchase option. After the stated initial Subscription Term it continues month-to-month at the stated monthly charge unless you give written notice of nonrenewal at least thirty days before the end of the initial term or a later monthly period. A later notice ends continuation at the first monthly period ending at least thirty days after receipt. We state the resulting termination date and return instructions promptly; we do not extend it because we delay responding. Any mandatory notice or shorter termination right under applicable law is preserved. You may return the Equipment by the termination date using the agreed tracked carrier and documented instructions. Billing stops on that termination date if the Equipment has been tendered to the agreed carrier by then, or earlier if we agree to accept an early return in writing. Our failure to provide a return address or reasonable return instructions may not prolong billing when you have made the Equipment reasonably available for return. Failure to return after termination may support only a lawful, documented claim under Section [[clause:subscription.default-remedies]], not indefinite renewed monthly billing plus full equipment value. Accrued lawful charges remain payable with credits for all collections. We retain ownership; return and accounting follow Sections [[clause:subscription.use-return-of-equipment-and-insurance]] and [[clause:subscription.default-remedies]].',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-01',
        findings: [
          'sub-3-7-notice-anchor-and-minimum-term',
          'sub-acceleration-double-recovery',
          'sub-purchase-residue',
        ],
      },
    ],
  },
  {
    slug: 'subscription.software-license',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'load-bearing',
      note: 'The equipment needs stated software-use rights and a boundary around manufacturer-owned software; selecting a receivables template cannot supply those license rights.',
    },
    version: 2,
    instrument: 'subscription',
    kind: 'clause',
    includeWhen: null,
    section: 'agreement',
    sortKey: 80,
    heading: 'Software License',
    body: 'We grant only the software rights that we own or are authorized to grant, as identified in the software schedule delivered before signing. No ownership or perpetual right in a manufacturer’s or other third party’s software is promised by this Agreement. Applicable third-party license terms, processor dependencies and support limitations must be supplied or made accessible before signing; an undisclosed external term may not expand your payment obligations under this Agreement. For software we own and identify in the schedule as included in the subscription, we grant a nonexclusive license to operate the Equipment during the paid term and any valid monthly continuation, ending on termination. No purchase or perpetual license is granted. A transfer of Equipment does not transfer software ownership, and no clause promises compatibility beyond our express commitments.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      { review: 'REVIEW-01', findings: [] },
      { review: 'REVIEW-02', findings: ['el-3-8-grants-no-licence-to-manufacturer-owned-software'] },
    ],
  },
  {
    slug: 'subscription.limitation-on-liability',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'no-alternative',
      note: 'The equipment provider’s liability exclusions and cap have no authored alternative; they are contractual allocations, not a requirement to disclaim liability.',
    },
    version: 2,
    instrument: 'subscription',
    kind: 'clause',
    includeWhen: null,
    section: 'agreement',
    sortKey: 90,
    heading: 'Limitation on Liability',
    body: 'Subject to the exceptions below, our aggregate liability for direct damages under this Agreement is limited to the scheduled charges paid or payable for the affected Equipment over the stated initial term. Neither party is liable to the other for consequential, incidental or special damages. These limitations do not apply to fraud, negligence causing personal injury or property damage, gross negligence, willful misconduct, breach of confidentiality or data-protection duties, infringement, title obligations, or liability that applicable law does not permit to be limited. They do not eliminate an express warranty, a right to reject nonconforming delivery, a required refund, or a remedy that applicable law makes nonwaivable. No disclaimer elsewhere enlarges these limitations.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      { review: 'REVIEW-01', findings: [] },
      {
        review: 'REVIEW-02',
        findings: [
          'el-3-9-excludes-personal-injury-and-omits-the-carve-out-3-11-has',
          'el-3-9-sole-and-exclusive-remedies-points-at-an-empty-set',
        ],
      },
    ],
  },
  {
    slug: 'subscription.warranties',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'no-alternative',
      note: 'Disclaiming equipment warranties is a commercial choice subject to statutory effectiveness requirements; no alternative warranty package is authored.',
    },
    version: 2,
    instrument: 'subscription',
    kind: 'clause',
    includeWhen: null,
    section: 'agreement',
    sortKey: 100,
    heading: 'Warranties',
    body: '(a) We warrant our authority to provide the Equipment and any rights we expressly grant, and that delivery will conform to the agreed description and express functionality promises. Written supplier warranties and the process for obtaining service will be supplied before signing. We do not disclaim our express warranties or prevent you from enforcing a supplier warranty to which you are entitled. TO THE EXTENT APPLICABLE LAW PERMITS, WE DISCLAIM IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THIS EXCLUSION DOES NOT LIMIT EXPRESS WARRANTIES OR ANY WARRANTY OR REMEDY THAT CANNOT LAWFULLY BE EXCLUDED. (b) You will use the Equipment for business purposes. This statement does not make an otherwise consumer transaction commercial, waive a required disclosure, or establish eligibility for an exemption.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      { review: 'REVIEW-01', findings: [] },
      { review: 'REVIEW-02', findings: ['el-3-9-sole-and-exclusive-remedies-points-at-an-empty-set'] },
    ],
  },
  {
    slug: 'subscription.indemnification',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'no-alternative',
      note: 'This equipment indemnity and its aggregate ceiling are the only authored allocation; the receivables funder’s guaranty choice does not decide it.',
    },
    version: 2,
    instrument: 'subscription',
    kind: 'clause',
    includeWhen: null,
    section: 'agreement',
    sortKey: 110,
    heading: 'Indemnification',
    body: 'You indemnify us against documented third-party claims to the extent caused by your material breach of this Agreement, negligence or willful misconduct in operating, altering or returning the Equipment. You do not indemnify us for our negligence, our breach, our fraud or misconduct, or the acts of persons for whom we are responsible. We must promptly notify you of a claim, permit a reasonable opportunity to participate in its defense and take reasonable steps to mitigate loss. Neither party may settle a claim imposing liability, an admission or a nonmonetary duty on the other without that party’s written consent. Your aggregate liability under this Section is capped at the scheduled monthly charges for the initial term; reasonable enforcement expenses also remain within the aggregate cost limit in Section [[clause:subscription.default-remedies]] and cannot be recovered twice. This indemnity imposes no liability on a guarantor beyond the separately signed Guaranty in Section [[clause:subscription.guaranty-of-payment]].',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      { review: 'REVIEW-01', findings: [] },
      {
        review: 'REVIEW-02',
        findings: [
          'el-3-9-excludes-personal-injury-and-omits-the-carve-out-3-11-has',
          'el-3-4a-declares-itself-exhaustive-and-is-not',
        ],
      },
    ],
  },
  {
    slug: 'subscription.default-remedies',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'no-alternative',
      note: 'The equipment contract has its own default, present-value acceleration and recovery rules; no alternative remedy package is authored for this provider.',
    },
    version: 2,
    instrument: 'subscription',
    kind: 'clause',
    includeWhen: null,
    section: 'agreement',
    sortKey: 120,
    heading: 'Default; Remedies',
    body: '(a) A material failure to perform an obligation actually due under this Agreement is a default only after written notice identifying the failure and ten business days after receipt to cure it, or any longer period required by law. A good-faith disputed invoice must be explained and corrected before its disputed portion is treated as overdue. A default or termination under a processing agreement, a receivables purchase agreement or any other agreement is not a default under this Agreement. (b) After an uncured default we may (i) terminate this Agreement’s future performance and require lawful return of the Equipment and payment of charges already earned and due, or (ii) seek actual damages available under the law governing the transaction. We do not automatically accelerate all future payments or label a fixed discount formula reasonable damages. Any future-payment claim must account for present value where required, avoided expense, mitigation, equipment recovery and other credits, and be established by a court or a separately signed settlement after the dispute. (c) Recovery must use lawful process. Self-help is permitted only where the governing law permits it, with no breach of the peace; this Agreement grants no advance permission to force entry. Mandatory notice, disposition, redemption, surplus, deficiency and acceptance-in-satisfaction requirements remain in force. Physical return alone is not an agreement to accept collateral in full satisfaction. We provide an itemized accounting of all payments, insurance proceeds, disposition proceeds or other legally required value credits, and reasonable permitted recovery expenses. No double recovery is allowed: equipment value cannot be recovered in addition to the same loss already satisfied by return, disposition or insurance. Any deficiency must be legally recoverable and proved, and any required surplus must be paid. (d) Actual, reasonable collection expenses, court costs and attorneys’ fees are recoverable only to the extent lawfully awarded or agreed in a separately signed post-dispute settlement. Across this Agreement, indemnity and Guaranty together, the aggregate cost limit is twenty-five percent (25%) of the non-fee amount lawfully recovered; no cost is counted twice or added to its own cap base. Each guarantor’s cost liability is also limited to twenty-five percent (25%) of that guarantor’s own non-fee liability and does not enlarge the aggregate cap. These cost limits create no obligation outside the limited scope of Section [[clause:subscription.guaranty-of-payment]]. (e) Setoff requires advance written itemization and an amount actually due between the same parties. Disputed damages may be set off only after judgment or a separately signed settlement. No equipment recovery or setoff increases the Purchased Amount, changes a receivables purchase’s Specified Percentage, or expands its guaranty.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-01',
        findings: [
          'sub-crossdefault-imports-frpa-default',
          'sub-acceleration-double-recovery',
          'sub-no-collection-channel-unbounded-setoff',
          'sub-payment-guaranty-defeats-commitment-3',
        ],
      },
      { review: 'REVIEW-02', findings: ['el-3-4a-declares-itself-exhaustive-and-is-not'] },
    ],
  },
  {
    slug: 'subscription.assignment',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'no-alternative',
      note: 'This separate provider’s assignment rights and customer-consent requirement have no authored alternative; a receivables assignment does not transfer this agreement.',
    },
    version: 1,
    instrument: 'subscription',
    kind: 'clause',
    includeWhen: null,
    section: 'agreement',
    sortKey: 130,
    heading: 'Assignment',
    body: 'You may not assign or transfer this Agreement, by operation of law or otherwise, without our prior written consent. For purposes of this Agreement, any transfer of voting control of you or your parent shall be considered an assignment or transfer hereof. We may assign or transfer this Agreement and our rights and obligations hereunder, in whole or in part, to any third party without the necessity of obtaining your consent.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: ['sub-ungrounded-upgrade-assumption-fees'] }],
  },
  /*
    THE SUBSCRIPTION HALF OF ONE REWRITE, and the reasons are NOT repeated here.
    They are set out in full above §3.14 in `equipment-lease/agreement.ts`, because
    a reason duplicated in two files is the twin problem in comment form:
    `twins.test.ts` checks that the two bodies agree and nothing checks that two
    prose explanations still do.
  */
  {
    slug: 'subscription.subscription-guaranty',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'load-bearing',
      note: 'This cross-reference and subordination rule must stay within the subscription guaranty’s defined obligations; the separate receivables guaranty does not supply them.',
    },
    version: 2,
    instrument: 'subscription',
    kind: 'clause',
    includeWhen: null,
    section: 'agreement',
    sortKey: 140,
    heading: 'Subscription Guaranty',
    body: 'Section [[clause:subscription.guaranty-of-payment]] states the entire separately signed Guaranty; this Section imposes no additional liability and does not guarantee monthly charges or business success. When a Guarantor pays a covered loss, that Guarantor receives subrogation rights to the extent of the payment, subject to preventing duplicate recovery and preserving our remaining claim for that same covered loss. We will reasonably document those rights. No general subordination of debts owed to a Guarantor is created, and no payment may be collected twice by routing it through this Section.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      { review: 'REVIEW-01', findings: [] },
      {
        review: 'REVIEW-02',
        findings: [
          'el-3-14-subordination-runs-in-the-wrong-direction',
          'el-3-14-was-not-conformed-when-4-2-was-narrowed',
        ],
      },
    ],
  },
  /*
    THE SUBSCRIPTION HALF OF ONE REWRITE, and the reasons are NOT repeated here.
    They are set out in full above §3.15 in `equipment-lease/agreement.ts`, because
    a reason duplicated in two files is the twin problem in comment form:
    `twins.test.ts` checks that the two bodies agree and nothing checks that two
    prose explanations still do.

    ONE THING IS TRUE OF THIS TWIN ONLY. The Article 9 sentence points at §3.6,
    and §3.6 is a declared divergence: the Equipment Lease claims a security
    interest outright and reserves the right to file a financing statement, while
    this document says the transaction "shall be treated as a lease" and claims a
    first lien only if a court finds Article 2A does not govern. The sentence is
    written to be true of both — it governs "a security interest described in
    Section 3.6", which is conditional here and unconditional there — so it needs
    no divergence of its own. If §3.7 ever gains the purchase option
    `lease-disclosure-assumes-a-purchase-option-the-subscription-does-not-grant`
    is holding open, read this sentence again.
  */
  {
    slug: 'subscription.governing-law-and-venue',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'misattributed',
      note: 'The funder’s venue and dispute facts concern its receivables purchase; this equipment provider’s contract has its own forum and procedural terms with no authored alternative.',
    },
    version: 2,
    instrument: 'subscription',
    kind: 'clause',
    includeWhen: null,
    section: 'agreement',
    sortKey: 150,
    heading: 'Governing Law and Venue',
    body: 'This Agreement is governed by the substantive law of the state of your principal place of business stated in the Subscriber and Equipment Information grid, subject to mandatory federal law and to applicable conflict-of-laws rules. An action arising out of or relating to this Agreement shall be brought in a state court of competent jurisdiction in that state, or in a federal court of competent jurisdiction sitting in that state. Neither you nor we may require the other to bring or defend such an action anywhere else, and nothing in this Section selects a court that lacks subject-matter jurisdiction. Where the law of a state fixes where an action under an agreement of this kind must be brought, that rule governs and this Section yields to it.\nPerfection, the effect of perfection or non-perfection, and the priority of a security interest described in Section [[clause:subscription.title-to-equipment]] are governed by the mandatory rules of the Uniform Commercial Code that apply to them. This Section does not vary those rules and does not choose the law that decides them.\nIf any part of this Agreement is not enforceable, the remaining provisions will remain valid and enforceable.\nService of a summons, a complaint or other legal process is governed by Section [[clause:subscription.independent-decision-governing-law]] and by the procedural law of the court in which the proceeding is brought. Nothing in this Section makes a mailing, an email or any other communication into service of legal process.\n',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      { review: 'REVIEW-01', findings: [] },
      {
        review: 'REVIEW-02',
        findings: [
          'el-3-15-hides-three-waivers-under-a-miscellaneous-caption',
          'el-3-15-jury-waiver-is-one-sided-where-the-frpas-is-mutual',
        ],
      },
    ],
  },
  {
    slug: 'subscription.jury-trial-waiver',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'misattributed',
      note: 'The funder’s venue and dispute facts concern its receivables purchase; this equipment provider’s contract has its own forum and procedural terms with no authored alternative.',
    },
    version: 1,
    instrument: 'subscription',
    includeWhen: null,
    section: 'agreement',
    sortKey: 150.1,
    heading: 'Jury Trial Waiver',
    body: 'You and we each waive trial by jury in an action arising out of or relating to this Agreement, to the extent the law of the forum gives effect to a waiver of that right made before a dispute has arisen. Where the law of the forum does not give effect to such a waiver, this Section has no effect and each of us retains the right to trial by jury. This waiver is mutual, it binds nobody who has not signed this Agreement, and it does not reach a claim applicable law requires to be tried to a jury.\n',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      { review: 'REVIEW-01', findings: [] },
      {
        review: 'REVIEW-02',
        findings: [
          'el-3-15-hides-three-waivers-under-a-miscellaneous-caption',
          'el-3-15-jury-waiver-is-one-sided-where-the-frpas-is-mutual',
        ],
      },
    ],
    kind: 'clause',
    derivedFrom: ['subscription.governing-law-and-venue'],
  },
  {
    slug: 'subscription.class-and-representative-proceedings',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'misattributed',
      note: 'The funder’s venue and dispute facts concern its receivables purchase; this equipment provider’s contract has its own forum and procedural terms with no authored alternative.',
    },
    version: 1,
    instrument: 'subscription',
    includeWhen: null,
    section: 'agreement',
    sortKey: 150.2,
    heading: 'Class and Representative Proceedings',
    body: 'No party waives a right to bring, to defend, or to take part in a class, collective, representative or public-enforcement proceeding that applicable law permits. Whether such a proceeding is available, and in what form, is for the court to determine under applicable law and its own rules. A party that takes part in one keeps whatever share of a recovery it is awarded and any right to costs or to a fee award that applicable law gives it.\n',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      { review: 'REVIEW-01', findings: [] },
      {
        review: 'REVIEW-02',
        findings: [
          'el-3-15-hides-three-waivers-under-a-miscellaneous-caption',
          'el-3-15-jury-waiver-is-one-sided-where-the-frpas-is-mutual',
        ],
      },
    ],
    kind: 'clause',
    derivedFrom: ['subscription.governing-law-and-venue'],
  },
  {
    slug: 'subscription.limitation-of-actions',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'misattributed',
      note: 'The funder’s venue and dispute facts concern its receivables purchase; this equipment provider’s contract has its own forum and procedural terms with no authored alternative.',
    },
    version: 1,
    instrument: 'subscription',
    includeWhen: null,
    section: 'agreement',
    sortKey: 150.3,
    heading: 'Limitation of Actions',
    body: 'The limitation period, the accrual rule, and any tolling or discovery rule that applicable law supplies apply to a claim by each party to this Agreement alike, whoever brings it and whoever it is brought against. This Agreement does not shorten any of them, and no other provision of this Agreement shortens one. A claim that applicable law does not permit to be shortened or given up is unaffected by this Agreement.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      { review: 'REVIEW-01', findings: [] },
      {
        review: 'REVIEW-02',
        findings: [
          'el-3-15-hides-three-waivers-under-a-miscellaneous-caption',
          'el-3-15-jury-waiver-is-one-sided-where-the-frpas-is-mutual',
        ],
      },
    ],
    kind: 'clause',
    derivedFrom: ['subscription.governing-law-and-venue'],
  },
  /*
    THE SUBSCRIPTION HALF OF ONE REWRITE, and the reasons are NOT repeated here.
    They are set out in full above §3.16 in `equipment-lease/agreement.ts`, because
    a reason duplicated in two files is the twin problem in comment form:
    `twins.test.ts` checks that the two bodies agree and nothing checks that two
    prose explanations still do.
  */
  {
    slug: 'subscription.notices',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'load-bearing',
      note: 'The separate equipment parties need notice destinations and effective-delivery rules distinct from judicial service; funder contact details do not replace them.',
    },
    version: 1,
    instrument: 'subscription',
    kind: 'clause',
    includeWhen: null,
    section: 'agreement',
    sortKey: 160,
    heading: 'Notices',
    body: 'All notices under this Agreement must be in writing, if to you at the address you give in the Subscriber and Equipment Information grid or at a later address you give us in writing, and if to us at _______________«43»_______________, Attn: Equipment Subscription Department, or at a later address we or a subsequent assignee give you in writing. Each of us will tell the other promptly in writing of a change of address.\nA notice is given (i) if sent by mail or courier, on the earlier of five (5) days after mailing or actual receipt or, in the case of courier, when delivered, and (ii) if sent by email, on transmission, provided no bounce-back or other non-delivery report is received. A notice given in any other manner is effective when actually received.\nSending a notice to an address a party has told the other it no longer uses does not make that notice effective, and a failure to give a change of address does not make an otherwise ineffective notice effective. A notice given under this Section is not service of legal process and is not evidence that service was made; service of a summons, a complaint or other legal process is governed by Section [[clause:subscription.independent-decision-governing-law]] and by the procedural law of the court.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: [] }],
  },
  {
    slug: 'subscription.electronic-signatures',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'no-alternative',
      note: 'This records the equipment parties’ agreement to electronic execution; legal recognition of electronic records does not require this particular consent clause.',
    },
    version: 1,
    instrument: 'subscription',
    kind: 'clause',
    includeWhen: null,
    section: 'agreement',
    sortKey: 170,
    heading: 'Electronic Signatures',
    body: 'The parties agree that electronic signatures (including those executed via any commercially recognized electronic-signature platform) shall have the same force and effect as original ink signatures. Electronic copies of this Agreement shall be treated as originals for all purposes.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: [] }],
  },
  {
    slug: 'subscription.entire-agreement',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'load-bearing',
      note: 'The equipment bargain needs an identified document set and signed-change rule so another transaction cannot silently amend it.',
    },
    version: 1,
    instrument: 'subscription',
    kind: 'clause',
    includeWhen: null,
    section: 'agreement',
    sortKey: 180,
    heading: 'Entire Agreement',
    body: 'This Agreement constitutes the entire agreement between the parties with respect to its subject matter, supersedes any previous agreements and understandings, and can be changed only by a written agreement signed by all parties. This Agreement may be executed in any number of counterparts and all of such counterparts taken together shall be deemed to constitute one and the same instrument.',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: [] }],
  },
  {
    slug: 'subscription.survival',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'load-bearing',
      note: 'The equipment contract needs to say which license, liability and guaranty duties continue after its term; no alternate survival package is authored.',
    },
    version: 2,
    instrument: 'subscription',
    kind: 'clause',
    includeWhen: null,
    section: 'agreement',
    sortKey: 190,
    heading: 'Survival',
    body: 'Sections [[clause:subscription.software-license]] (Software License), [[clause:subscription.limitation-on-liability]] (Limitation on Liability), [[clause:subscription.indemnification]] (Indemnification) and [[clause:subscription.subscription-guaranty]] (Subscription Guaranty) survive the expiry or termination of this Agreement.\n',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: [] }],
  },
];
