"""Which changed files genuinely touch upstream code.

The fork rule is that upstream files are modified only through
`overlays/*.patch`. Deciding what counts as "upstream" by PATH alone is wrong
in one unavoidable case: Remix resolves routes by filename, so a route we write
must live in `apps/remix/app/routes/` and cannot go in a package. Those files
have never existed upstream.

Before ownership was declarable, this guard failed on every lease-builder PR
and each was merged over the failure — which is how a guard stops being read,
and is the same class of silence as PR #1 merging red and the E2E gate going
dark twice (docs/STATE.md).

Ownership is therefore declared in overlays/BIZRETHINK-OWNED.txt and reviewed
like anything else, rather than inferred from a path prefix.
"""

import re
import sys

# Ours outright.
EXEMPT_PREFIXES = ('packages/bizrethink/',)

# Generated by merge-into-schema.mjs from prisma-extensions/additions.prisma.
EXEMPT_EXACT = ('packages/prisma/schema.prisma',)

# Established precedent: BizRethink migrations already live alongside
# upstream's, and splitting them would break `prisma migrate deploy`.
EXEMPT_PREFIXES += ('packages/prisma/migrations/',)

WATCHED_ROOTS = ('apps/', 'packages/')


def to_regex(glob: str) -> re.Pattern[str]:
    """Anchored, with `*` confined to a single path segment.

    Segment-confined on purpose: a declared `lease/*.tsx` must not quietly
    exempt `lease/nested/deep.tsx`, or the declaration stops meaning what it
    says the moment someone adds a subdirectory.
    """
    return re.compile('^' + re.escape(glob).replace(r'\*', '[^/]*') + '$')


def read_globs(path: str) -> list[str]:
    with open(path, encoding='utf-8') as handle:
        return [
            line.strip()
            for line in handle
            if line.strip() and not line.lstrip().startswith('#')
        ]


def main(changed_path: str, owned_path: str) -> int:
    globs = read_globs(owned_path)
    owned = [to_regex(glob) for glob in globs]

    print('BizRethink-owned path patterns:', file=sys.stderr)
    for glob in globs:
        print(f'  {glob}', file=sys.stderr)

    with open(changed_path, encoding='utf-8') as handle:
        changed = [line.strip() for line in handle if line.strip()]

    for path in changed:
        if not path.startswith(WATCHED_ROOTS):
            continue
        if path.startswith(EXEMPT_PREFIXES) or path in EXEMPT_EXACT:
            continue
        if any(pattern.match(path) for pattern in owned):
            continue

        print(path)

    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1], sys.argv[2]))
