import type { McaClause } from '../types';

/**
 * The Payzli Split Funding Authorization — a letter, and it has no numbered clauses at all.
 */
export const PAYZLI_LETTER: McaClause[] = [
  {
    slug: 'split-funding.frpa-recital',
    version: 1,
    instrument: 'split-funding',
    kind: 'clause',
    number: '',
    heading: '',
    body: 'I am writing on behalf of _____________«1»______________ (the “Seller”). Pursuant to the Future Receivables Purchase Agreement dated ____«9»____ between Seller and ________«8»________ (the “Funding Company”) (the “Purchase Agreement”), Seller has sold certain credit and debit card receivables to Funding Company, and Seller has agreed to pay _«2»_% of payments due Seller from United Payment Systems LLC, doing business as {{processor}} (“{{processor}}”), pursuant to that Merchant Processing Agreement executed by {{processor}} and Seller (the “{{processor}} Merchant Agreement”).',
    section: 'letter',
    sortKey: 10,
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-01',
        findings: ['payzli-two-widgets-for-one-percentage', 'payzli-unbounded-irrevocable-instruction'],
      },
    ],
  },
  {
    slug: 'split-funding.split-funding-instruction',
    version: 1,
    instrument: 'split-funding',
    kind: 'clause',
    number: '',
    heading: '',
    body: 'Pursuant to the {{processor}} Merchant Agreement, Seller hereby irrevocably instructs {{processor}} to (a) withhold or debit, in each case only from the payments due from {{processor}} to Seller and not from any deposit account of Seller, _«3»_% of the payments due from {{processor}} to Seller under the {{processor}} Merchant Agreement arising from credit and debit card transactions, and (b) forward the amount so withheld to Funding Company, until Funding Company notifies {{processor}} in writing that Seller’s obligations under the Purchase Agreement have been satisfied. The Purchased Amount under the Purchase Agreement is $ _____«16»______; that figure is stated for information only and is not the point at which withholding stops, because Seller’s obligations under the Purchase Agreement may include fees in addition to the Purchased Amount. This instruction relates only to the Purchase Agreement and secures no other obligation. Seller may also instruct {{processor}} to cease withholding on producing Funding Company’s written confirmation that the Completion Threshold has been attained, which Funding Company shall provide within two Workdays (as defined in the Purchase Agreement) of a written request.',
    section: 'letter',
    sortKey: 20,
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      {
        review: 'REVIEW-01',
        findings: [
          'payzli-no-remittance-instructions',
          'payzli-two-widgets-for-one-percentage',
          'payzli-unbounded-irrevocable-instruction',
        ],
      },
      {
        review: 'REVIEW-02',
        findings: [
          'payzli-cessation-on-notice-vs-frpa-2-6-automatic-cessation',
          'payzli-instruction-stops-short-of-the-frpa-completion-threshold',
          'payzli-uses-debit-where-the-frpa-promises-no-deposit-account-debiting',
        ],
      },
    ],
  },
  {
    slug: 'split-funding.satisfaction-of-payzlis-obligation',
    version: 1,
    instrument: 'split-funding',
    kind: 'clause',
    number: '',
    heading: '',
    body: 'Such payments to Funding Company shall be made in partial or complete satisfaction of any obligation {{processor}} may have to Seller under the {{processor}} Merchant Agreement.',
    section: 'letter',
    sortKey: 30,
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
  },
  {
    slug: 'split-funding.fees-are-additional',
    version: 1,
    instrument: 'split-funding',
    kind: 'clause',
    number: '',
    heading: '',
    body: 'SELLER ACKNOWLEDGES THAT SUCH PAYMENTS TO FUNDING COMPANY ARE IN ADDITION TO ANY FEES OWED BY SELLER TO PAYZLI PURSUANT TO THE PAYZLI MERCHANT AGREEMENT OR ANY OTHER AGREEMENT BETWEEN SELLER AND PAYZLI.',
    section: 'letter',
    sortKey: 40,
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
  },
  {
    slug: 'split-funding.processor-termination-fees',
    version: 1,
    instrument: 'split-funding',
    kind: 'clause',
    number: '',
    heading: '',
    body: 'Seller hereby acknowledges that the {{processor}} Merchant Agreement provides that (i) if the Merchant Processing Agreement is terminated by Seller within one year of the Merchant Processing Agreement’s effective date, then Seller is obligated to pay {{processor}} a termination fee equal to the lesser of $295.00 or the maximum amount allowed by law; and (ii) if the Merchant Processing Agreement is terminated by Seller more than one year after the Merchant Processing Agreement’s effective date, then Seller is obligated to pay {{processor}} a termination fee equal to the lesser of $195.00 or the maximum amount allowed by law.',
    section: 'letter',
    sortKey: 50,
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: ['payzli-hardcoded-third-party-termination-fees'] }],
  },
  {
    slug: 'split-funding.indemnity',
    version: 1,
    instrument: 'split-funding',
    kind: 'clause',
    number: '',
    heading: '',
    body: 'Seller hereby agrees to indemnify {{processor}} from any and all losses, damages, claims, liabilities, and expenses, including reasonable attorneys’ fees, arising from {{processor}}’s following the instructions set forth in this letter.',
    section: 'letter',
    sortKey: 60,
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: ['payzli-indemnity-runs-only-against-merchant'] }],
  },
  {
    slug: 'split-funding.remittance-instructions',
    version: 1,
    instrument: 'split-funding',
    kind: 'clause',
    number: '',
    heading: '',
    body: 'Remittance instructions. Forward the withheld amounts to: ___________«10»___________ (Funding Company), _______________«11»_______________; bank _________«12»_________, routing number ___«13»____, account number _____«14»_____. Questions about this authorization: _________«15»_________.',
    section: 'letter',
    sortKey: 70,
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: ['payzli-no-remittance-instructions'] }],
  },
];
