import {
  MCA_EQUIPMENT_FIELDS,
  MCA_FUNDING_FIELDS,
  MCA_ISO_FIELDS,
  mcaGuarantorFields,
  retiredGuarantorSsn,
} from '../clauses/fields';
import type { McaReusableContent } from '../clauses/types';
import { MCA_EXECUTION_CONTENT } from './execution';

/** Extracted/required content. Moving an identity never transfers its approval. */
export const ALL_MCA_REUSABLE: McaReusableContent[] = [
  ...MCA_EXECUTION_CONTENT,
  {
    slug: 'frpa.merchant-and-funding-information',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'load-bearing',
      note: 'The parties, funding figures, itemized deductions and notice contacts must be completed for this purchase to operate; changing deal values does not select different wording.',
    },
    version: 5,
    instrument: 'frpa',
    includeWhen: null,
    section: 'funding-terms',
    sortKey: 0,
    heading: 'Merchant and Funding Information',
    body: '',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
    kind: 'field-group',
    uses: ['document', 'template'],
    placement: { section: 'funding-terms', edge: 'start' },
    fields: MCA_FUNDING_FIELDS,
  },
  {
    slug: 'equipment-lease.guarantor-information',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'misattributed',
      note: 'These fields identify the equipment provider’s guarantor, not the receivables funder’s; the FRPA guaranty-scope answer cannot decide this separate guaranty.',
    },
    version: 3,
    instrument: 'equipment-lease',
    includeWhen: null,
    section: 'guaranty',
    sortKey: 10,
    heading: 'Guarantor Information',
    body: '',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
    kind: 'field-group',
    uses: ['document', 'template'],
    placement: { section: 'guaranty', edge: 'start' },
    fields: mcaGuarantorFields({ name: '«21»', address: '«23»', phone: '«24»' }),
    repeatFor: 'guarantor',
    retiredFields: [retiredGuarantorSsn('«22»')],
  },
  {
    slug: 'subscription.guarantor-information',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'misattributed',
      note: 'These fields identify the equipment provider’s guarantor, not the receivables funder’s; the FRPA guaranty-scope answer cannot decide this separate guaranty.',
    },
    version: 3,
    instrument: 'subscription',
    includeWhen: null,
    section: 'guaranty',
    sortKey: 10,
    heading: 'Guarantor Information',
    body: '',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: [] }],
    kind: 'field-group',
    uses: ['document', 'template'],
    placement: { section: 'guaranty', edge: 'start' },
    fields: mcaGuarantorFields({ name: '«21»', address: '«23»', phone: '«24»' }),
    repeatFor: 'guarantor',
    retiredFields: [retiredGuarantorSsn('«22»')],
  },
  {
    slug: 'iso-pra.parties',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'load-bearing',
      note: 'The referral agreement needs the actual Company and ISO Partner identified; merchant transaction fields do not identify the parties to this channel contract.',
    },
    version: 3,
    instrument: 'iso-pra',
    includeWhen: null,
    section: 'commission',
    sortKey: 1,
    heading: 'Parties',
    body: 'This ISO Partner Referral Agreement (the “Agreement”) is entered into and effective as of {{field:iso.effectiveDate}} (the “Effective Date”) by and between {{field:iso.companyLegalName}} (“Company”), and {{field:iso.partnerLegalName}} (“ISO Partner”).',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: [] }],
    kind: 'document-block',
    uses: ['document', 'template'],
    placement: { section: 'commission', edge: 'start' },
    fields: MCA_ISO_FIELDS,
  },
  {
    slug: 'iso-pra.recital-company-business',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'no-alternative',
      note: 'This recital describes the Company’s financing business; no different business recital is authored for a funder answer.',
    },
    version: 2,
    instrument: 'iso-pra',
    includeWhen: null,
    section: 'commission',
    sortKey: 2,
    heading: 'Company Business',
    body: 'WHEREAS, Company is engaged in the business of providing merchant cash advance (“MCA”) funding and related financial products to small and mid-sized businesses throughout the United States; and',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: [] }],
    kind: 'document-block',
    uses: ['document', 'template'],
    placement: { section: 'commission', edge: 'start' },
  },
  {
    slug: 'iso-pra.recital-partner-purpose',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'load-bearing',
      note: 'The recital identifies the referral relationship and points to its commission bargain; removing the merchant channel entirely is an instrument choice, not alternate recital wording.',
    },
    version: 2,
    instrument: 'iso-pra',
    includeWhen: null,
    section: 'commission',
    sortKey: 3,
    heading: 'Referral Relationship',
    body: 'WHEREAS, ISO Partner desires to introduce prospective merchants to Company for payment processing, with merchant cash advance funding available to those merchants through Company’s ordinary underwriting path, in exchange for commission compensation as described herein;',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: ['iso-recital-funding-not-processing'] }],
    kind: 'document-block',
    uses: ['document', 'template'],
    placement: { section: 'commission', edge: 'start' },
  },
  {
    slug: 'iso-pra.consideration',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'no-alternative',
      note: 'This is the only authored recital of the referral parties’ mutual promises; no statute is identified as prescribing the recital.',
    },
    version: 2,
    instrument: 'iso-pra',
    includeWhen: null,
    section: 'commission',
    sortKey: 4,
    heading: 'Mutual Consideration',
    body: 'NOW THEREFORE, in consideration of the mutual promises and commitments contained herein, the parties agree as follows:',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: [] }],
    kind: 'document-block',
    uses: ['document', 'template'],
    placement: { section: 'commission', edge: 'start' },
  },
  {
    slug: 'frpa.holdback-prompt',
    whyThisClause: {
      kind: 'implements',
      citation:
        'O.C.G.A. §10-1-393.18(e)(4); Utah Code §7-27-202(3); K.S.A. §75-784(b)(5); Mo. Rev. Stat. §427.300.3(2)(e) (variable-payment methodology in covered agreements)',
    },
    variance: {
      kind: 'fixed',
      because: 'no-alternative',
      note: 'The estimate must remain distinct from the actual percentage collection; the collection-method answers currently provide no alternative explanation backed by ACH terms.',
    },
    version: 1,
    instrument: 'frpa',
    includeWhen: null,
    section: 'funding-terms',
    sortKey: 9.9,
    heading: 'Holdback interview prompt',
    body: 'What is the Estimated Daily Holdback? ',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: ['US-GA', 'US-UT', 'US-KS', 'US-MO'],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
    kind: 'guidance',
    uses: ['interview'],
    placement: null,
    derivedFrom: ['frpa.holdback-explainer'],
  },
  {
    slug: 'frpa.equipment-cost-prompt',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'misattributed',
      note: 'The funder decides whether equipment is offered; the merchant chooses purchase or lease. This explanation must cover both merchant elections whenever equipment is offered.',
    },
    version: 1,
    instrument: 'frpa',
    includeWhen: (facts) => facts.equipment !== 'none',
    section: 'funding-terms',
    sortKey: 19.9,
    heading: 'Equipment interview prompt',
    body: 'What is the Equipment Cost? ',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
    kind: 'guidance',
    uses: ['interview'],
    placement: null,
    derivedFrom: ['frpa.equipment-cost-explainer'],
  },
  {
    slug: 'frpa.party-identification',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'load-bearing',
      note: 'The purchase needs identified contracting parties, an effective date and a funding trigger; a processor or affiliate does not become a party merely by being named.',
    },
    version: 2,
    instrument: 'frpa',
    includeWhen: null,
    section: 'preamble',
    sortKey: 9.9,
    heading: 'Party identification',
    body: 'This Future Receivables Purchase Agreement (this “Agreement”) is entered into as of {{field:funding.effectiveDate}} (the “Effective Date”) by {{funder}}, a {{field:provider.entityType}} organized under the laws of {{field:provider.organizationState}}, with its principal office at {{field:provider.principalAddress}} (the “Buyer”), and {{field:merchant.legalName}} (the “Merchant”), identified by its full legal name, entity type and state of organization in the Merchant and Funding Information grid. ',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
    kind: 'document-block',
    uses: ['document', 'template'],
    placement: { before: 'frpa.parties' },
    derivedFrom: ['frpa.parties'],
  },
  {
    slug: 'frpa.execution-legend',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'load-bearing',
      note: 'Merchant’s authorized signature and a guarantor’s separate capacity must be distinguishable; the agreement cannot operate without execution by its actual parties.',
    },
    version: 1,
    instrument: 'frpa',
    includeWhen: null,
    section: 'execution',
    sortKey: 39.9,
    heading: 'Execution legend',
    body: 'IN WITNESS WHEREOF, the parties execute this Agreement as of the dates written beside their signatures.\n',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
    kind: 'document-block',
    uses: ['document', 'template'],
    placement: { before: 'frpa.execution' },
    derivedFrom: ['frpa.execution'],
  },
  {
    slug: 'equipment-lease.party-identification',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'load-bearing',
      note: 'The equipment agreement needs its own provider, customer and effective date; the receivables funder’s profile does not identify these contracting parties.',
    },
    version: 1,
    instrument: 'equipment-lease',
    includeWhen: null,
    section: 'agreement',
    sortKey: 0.9,
    heading: 'Party identification',
    body: 'This Equipment Lease Agreement (this “Agreement”) is made between {{field:equipment.providerLegalName}}, a {{field:equipment.providerEntityType}} formed in {{field:equipment.providerFormationState}}, with its principal office at {{field:equipment.providerAddress}} (“we,” “us,” or “our”), and the Lessee identified in the Lessee and Equipment Information grid (“you” or “your”). ',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
    kind: 'document-block',
    uses: ['document', 'template'],
    placement: { before: 'equipment-lease.parties' },
    derivedFrom: ['equipment-lease.parties'],
  },
  {
    slug: 'equipment-lease.merchant-and-equipment-information',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'load-bearing',
      note: 'These equipment-specific identities, amounts, dates and operating terms must be completed for the selected equipment document; their values are not provider wording alternatives.',
    },
    version: 2,
    instrument: 'equipment-lease',
    includeWhen: null,
    section: 'agreement',
    sortKey: 0,
    heading: 'Lessee and Equipment Information',
    body: '',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
    kind: 'field-group',
    uses: ['document', 'template'],
    placement: { before: 'equipment-lease.party-identification' },
    derivedFrom: ['equipment-lease.parties'],
    fields: MCA_EQUIPMENT_FIELDS,
  },
  {
    slug: 'equipment-lease.guaranty-heading',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'load-bearing',
      note: 'The equipment contract needs to say which license, liability and guaranty duties continue after its term; no alternate survival package is authored.',
    },
    version: 1,
    instrument: 'equipment-lease',
    includeWhen: null,
    section: 'guaranty',
    sortKey: 0,
    heading: 'Guaranty section heading',
    body: 'Section [[section:guaranty]]: Personal Guaranty',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
    kind: 'document-block',
    uses: ['document', 'template'],
    placement: { section: 'guaranty', edge: 'start' },
    derivedFrom: ['equipment-lease.survival'],
  },
  {
    slug: 'subscription.party-identification',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'load-bearing',
      note: 'The equipment agreement needs its own provider, customer and effective date; the receivables funder’s profile does not identify these contracting parties.',
    },
    version: 1,
    instrument: 'subscription',
    includeWhen: null,
    section: 'agreement',
    sortKey: 0.9,
    heading: 'Party identification',
    body: 'This Subscription Agreement (this “Agreement”) is made between {{field:equipment.providerLegalName}}, a {{field:equipment.providerEntityType}} formed in {{field:equipment.providerFormationState}}, with its principal office at {{field:equipment.providerAddress}} (“we,” “us,” or “our”), and the Subscriber identified in the Subscriber and Equipment Information grid (“you” or “your”). ',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: [] }],
    kind: 'document-block',
    uses: ['document', 'template'],
    placement: { before: 'subscription.parties' },
    derivedFrom: ['subscription.parties'],
  },
  {
    slug: 'subscription.merchant-and-equipment-information',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'load-bearing',
      note: 'These equipment-specific identities, amounts, dates and operating terms must be completed for the selected equipment document; their values are not provider wording alternatives.',
    },
    version: 2,
    instrument: 'subscription',
    includeWhen: null,
    section: 'agreement',
    sortKey: 0,
    heading: 'Subscriber and Equipment Information',
    body: '',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: [] }],
    kind: 'field-group',
    uses: ['document', 'template'],
    placement: { before: 'subscription.party-identification' },
    derivedFrom: ['subscription.parties'],
    fields: MCA_EQUIPMENT_FIELDS,
  },
  {
    slug: 'subscription.guaranty-heading',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'load-bearing',
      note: 'The equipment contract needs to say which license, liability and guaranty duties continue after its term; no alternate survival package is authored.',
    },
    version: 1,
    instrument: 'subscription',
    includeWhen: null,
    section: 'guaranty',
    sortKey: 0,
    heading: 'Guaranty section heading',
    body: 'Section [[section:guaranty]]: Personal Guaranty',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-01', findings: [] }],
    kind: 'document-block',
    uses: ['document', 'template'],
    placement: { section: 'guaranty', edge: 'start' },
    derivedFrom: ['subscription.survival'],
  },
  {
    slug: 'frpa.prior-transaction-fields',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'load-bearing',
      note: 'A renewal using either settlement method needs a completed record of the merchant’s election and resulting cash; the no-renewal answer omits this record rather than selecting alternative wording.',
    },
    version: 1,
    instrument: 'frpa',
    includeWhen: (facts) => facts.renewalModel !== 'none',
    section: 'funding-terms',
    sortKey: 39.9,
    heading: 'Prior transaction treatment',
    body: '',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [{ review: 'REVIEW-02', findings: [] }],
    kind: 'field-group',
    uses: ['document', 'template'],
    placement: { before: 'frpa.rollover-method-election' },
    derivedFrom: ['frpa.rollover-method-election'],
    fields: [
      {
        binding: 'funding.priorTransactionTreatment',
        label: 'Prior transaction treatment',
        widget: '{{field:funding.priorTransactionTreatment}}',
        legacyWidget: '«25»',
        kind: 'text',
        required: true,
      },
    ],
  },
  {
    slug: 'frpa.guarantor-fields',
    whyThisClause: { kind: 'discretionary' },
    variance: {
      kind: 'fixed',
      because: 'load-bearing',
      note: 'An elected guaranty needs identified guarantors and signatures in the correct capacity; no-guaranty templates omit these fields, and the same identity rule serves both guaranty scopes.',
    },
    version: 1,
    instrument: 'frpa',
    includeWhen: (facts) => facts.guarantyScope !== 'none',
    section: 'guaranty',
    sortKey: 10.1,
    heading: 'Guarantor identity and signature',
    body: '',
    source: { kind: 'attorney-drafted', author: null },
    status: 'draft',
    appliesInStates: [],
    examinedBy: [
      { review: 'REVIEW-01', findings: ['frpa-guarantor-widget-bound-to-merchant'] },
      { review: 'REVIEW-02', findings: ['frpa-9-5-refers-to-guarantors-the-form-cannot-collect'] },
    ],
    kind: 'field-group',
    uses: ['document', 'template'],
    placement: { after: 'frpa.guarantor-information-9-1' },
    derivedFrom: ['frpa.guarantor-information-9-1'],
    fields: mcaGuarantorFields({ name: '«35»', capacity: '«36»', address: '«38»', phone: '«39»', email: '«40»' }),
    repeatFor: 'guarantor',
    retiredFields: [retiredGuarantorSsn('«37»')],
  },
];
