import type { TEnvelope } from '@documenso/lib/types/envelope';
import type { Field, Recipient } from '@prisma/client';
import {
  DocumentDistributionMethod,
  DocumentSigningOrder,
  DocumentSource,
  DocumentStatus,
  DocumentVisibility,
  EnvelopeType,
  FieldType,
  Prisma,
  ReadStatus,
  RecipientRole,
  SendStatus,
  SigningStatus,
  TemplateType,
} from '@prisma/client';

export const recipientFixture = (envelopeId: string): Recipient => ({
  id: 1,
  envelopeId,
  sentAt: null,
  lastReminderSentAt: null,
  nextReminderAt: null,
  reminderCount: 0,
  email: 'owner@example.invalid',
  name: 'Synthetic recipient',
  token: 'synthetic-recipient-token',
  role: RecipientRole.SIGNER,
  readStatus: ReadStatus.NOT_OPENED,
  signingStatus: SigningStatus.NOT_SIGNED,
  sendStatus: SendStatus.NOT_SENT,
  documentDeletedAt: null,
  expired: null,
  expiresAt: null,
  expirationNotifiedAt: null,
  signedAt: null,
  authOptions: null,
  signingOrder: null,
  rejectionReason: null,
});

export const envelopeFixture = (overrides: Partial<TEnvelope> = {}): TEnvelope => ({
  id: 'envelope_team_a',
  secondaryId: 'document_1',
  internalVersion: 2,
  type: EnvelopeType.DOCUMENT,
  status: DocumentStatus.DRAFT,
  source: DocumentSource.DOCUMENT,
  visibility: DocumentVisibility.EVERYONE,
  templateType: TemplateType.PRIVATE,
  externalId: null,
  createdAt: new Date('2026-09-12T00:00:00Z'),
  updatedAt: new Date('2026-09-12T00:00:00Z'),
  completedAt: null,
  deletedAt: null,
  title: 'Synthetic team A document',
  authOptions: null,
  formValues: null,
  publicTitle: '',
  publicDescription: '',
  userId: 7,
  teamId: 10,
  folderId: null,
  templateId: null,
  documentMeta: {
    id: 'meta_test',
    signingOrder: DocumentSigningOrder.PARALLEL,
    distributionMethod: DocumentDistributionMethod.EMAIL,
    subject: null,
    message: null,
    timezone: 'Etc/UTC',
    dateFormat: 'yyyy-MM-dd',
    redirectUrl: null,
    typedSignatureEnabled: true,
    uploadSignatureEnabled: true,
    drawSignatureEnabled: true,
    allowDictateNextSigner: false,
    language: 'en',
    emailSettings: null,
    emailId: null,
    emailReplyTo: null,
    envelopeExpirationPeriod: null,
  },
  recipients: [],
  fields: [],
  envelopeItems: [],
  directLink: null,
  team: { id: 10, url: 'team-a' },
  user: { id: 7, name: 'Synthetic owner', email: 'owner@example.invalid' },
  ...overrides,
});

export const fieldFixture = (type: FieldType = FieldType.TEXT): Field => ({
  id: 5,
  secondaryId: 'field_test',
  envelopeId: 'envelope_team_a',
  envelopeItemId: 'item_test',
  recipientId: 1,
  type,
  page: 1,
  positionX: new Prisma.Decimal(10),
  positionY: new Prisma.Decimal(10),
  width: new Prisma.Decimal(20),
  height: new Prisma.Decimal(5),
  customText: '',
  inserted: false,
  fieldMeta: type === FieldType.TEXT ? { type: 'text' } : null,
});
